//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusMods.Games.FOMOD.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusMods.Games.FOMOD.UI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FooterStepperView_FooterStepperView_Finish {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string FooterStepperView_FooterStepperView_Next {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more groups failed validation..
        /// </summary>
        public static string FooterStepperView_FooterStepperView_One_or_more_groups_failed_validation_ {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_One_or_more_groups_failed_validation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string FooterStepperView_FooterStepperView_Previous {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select at least one).
        /// </summary>
        public static string GuidedInstallerGroupView_SelectAtLeastOne {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupView_SelectAtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_None {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select nothing.
        /// </summary>
        public static string GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Select_nothing {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Select_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option to select nothing.
        /// </summary>
        public static string GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Use_this_option_to_select_nothing {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Use_this_option_to_se" +
                        "lect_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation complete.
        /// </summary>
        public static string GuidedInstallerStepView_GuidedInstallerStepView_Installation_complete {
            get {
                return ResourceManager.GetString("GuidedInstallerStepView_GuidedInstallerStepView_Installation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional details available.
        /// </summary>
        public static string GuidedInstallerStepView_GuidedInstallerStepView_No_additional_details_available {
            get {
                return ResourceManager.GetString("GuidedInstallerStepView_GuidedInstallerStepView_No_additional_details_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional details.
        /// </summary>
        public static string HighlightedOptionDescription_No_Extra_Details {
            get {
                return ResourceManager.GetString("HighlightedOptionDescription_No_Extra_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your mod has been successfully installed with the selected options. /// ///If you ever want to change your choices, simply reinstall the mod. Your settings can be adjusted at any time..
        /// </summary>
        public static string InstallationCompleteScreenText {
            get {
                return ResourceManager.GetString("InstallationCompleteScreenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Option Mod.
        /// </summary>
        public static string MultiOptionHeader_Multi_Option_Mod {
            get {
                return ResourceManager.GetString("MultiOptionHeader_Multi_Option_Mod", resourceCulture);
            }
        }
    }
}
