using FluentAssertions;
using NexusMods.Abstractions.GameLocators;
using NexusMods.Abstractions.Loadouts.Files;
using NexusMods.Abstractions.NexusWebApi.Types;
using NexusMods.Games.TestFramework;
using NexusMods.Hashing.xxHash64;
using ModId = NexusMods.Abstractions.NexusWebApi.Types.ModId;
// ReSharper disable StringLiteralTypo

namespace NexusMods.Games.RedEngine.Tests;

[Trait("RequiresNetworking", "True")]
public class ModInstallerTests : AGameTest<Cyberpunk2077>
{
    public ModInstallerTests(IServiceProvider provider) : base(provider) { }

    [Theory]
    [MemberData(nameof(TestFiles))]
    public async Task CanCreateLoadout(string name, ModId modId, FileId fileId,
        Hash hash, IEnumerable<GamePath> files)
    {
        var loadout = await CreateLoadout(indexGameFiles:false);
        var id = await DownloadAndCacheMod(GameInstallation.Game.Domain, modId, fileId, hash);
        var mod = await InstallModStoredFileIntoLoadout(loadout, id, name);

        mod.Files
            .Select(file => file.To)
            .Should()
            .BeEquivalentTo(files, opt => opt.WithoutStrictOrdering());
    }

    public static IEnumerable<object[]> TestFiles => new[]
    {
        new object[]
        {
            "Cyber Engine Tweaks", ModId.From(107), FileId.From(33156),
            Hash.From(0x8BCFFD83A0F5FC71), new[]
            {
                "bin/x64/LICENSE",
                "bin/x64/global.ini",
                "bin/x64/plugins/cyber_engine_tweaks.asi",
                "bin/x64/plugins/cyber_engine_tweaks/ThirdParty_LICENSES",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSans-Regular.ttf",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSansJP-Regular.otf",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSansKR-Regular.otf",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSansMono-Regular.ttf",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSansSC-Regular.otf",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSansTC-Regular.otf",
                "bin/x64/plugins/cyber_engine_tweaks/fonts/NotoSansThai-Regular.ttf",
                "bin/x64/plugins/cyber_engine_tweaks/scripts/json/LICENSE",
                "bin/x64/plugins/cyber_engine_tweaks/scripts/json/README.md",
                "bin/x64/plugins/cyber_engine_tweaks/scripts/json/json.lua",
                "bin/x64/plugins/cyber_engine_tweaks/tweakdb/tweakdbstr.kark",
                "bin/x64/plugins/cyber_engine_tweaks/tweakdb/usedhashes.kark",
                "bin/x64/version.dll",
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Redscript", ModId.From(1511), FileId.From(36622),
            Hash.From(0x8BEF15CA909D8543), new[]
            {
                "engine/config/base/scripts.ini",
                "engine/tools/scc.exe",
                "r6/config/cybercmd/scc.toml"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "cybercmd", ModId.From(5176), FileId.From(34566),
            Hash.From(0xEE78A096C8565B99), new[]
            {
                "bin/x64/plugins/cybercmd.asi",
            }.Select(p => new GamePath(LocationId.Game, p))
        },

        new object[]
        {
            "Archive-XL", ModId.From(4198), FileId.From(36969),
            Hash.From(0x1D30861A46BA7B8E), new[]
            {
                "r6/scripts/ArchiveXL/ArchiveXL.reds",
                "red4ext/plugins/ArchiveXL/ArchiveXL.dll"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Tweak-XL", ModId.From(4197), FileId.From(36048),
            Hash.From(0x22A45B59423201E1), new[]
            {
                "r6/scripts/TweakXL/TweakXL.reds",
                "red4ext/plugins/TweakXL/TweakXL.dll"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Panam Romanced Enhanced", ModId.From(4626), FileId.From(38117),
            Hash.From(0xDD0E1C3AEA20E6C1), new[]
            {
                "archive/pc/mod/PanamPrivacy.archive",
                "archive/pc/mod/PanamRomancedEnhanced.archive",
                "archive/pc/mod/PanamRomancedEnhancedPrivacy.archive"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Panam Romanced Enhanced REDmod", ModId.From(4626),
            FileId.From(38118), Hash.From(0x46F5AD6A75172F76), new[]
            {
                "mods/PanamRomancedEnhanced/archives/PanamRomancedEnhanced.archive",
                "mods/PanamRomancedEnhanced/info.json",
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Tarnished Pack", ModId.From(6072), FileId.From(31953),
            Hash.From(0x0AAFB35F889500BD), new[]
            {
                "archive/pc/mod/WINGDEER_FemV_HAIR_TARNISHED1_no1.archive",
                "archive/pc/mod/WINGDEER_FemV_HAIR_TARNISHED2_no1.archive",
                "archive/pc/mod/WINGDEER_FemV_HAIR_TARNISHED3_no1.archive",
                "archive/pc/mod/WINGDEER_FemV_HAIR_TARNISHED4_no1.archive",
                "archive/pc/mod/WINGDEER_FemV_HAIR_TARNISHED5_no1.archive",
                "archive/pc/mod/WINGDEER_FemV_HAIR_TARNISHED6_no1.archive"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Spicy Valentina", ModId.From(7404), FileId.From(39175),
            Hash.From(0xB354E2BE032A947F), new[]
            {
                "bin/x64/plugins/cyber_engine_tweaks/mods/AppearanceChangeUnlocker/character-preset/female/SPICY VALENTINA.preset",
                "bin/x64/plugins/cyber_engine_tweaks/mods/AppearanceChangeUnlocker/character-preset/male/SPICY VALENTINA.preset"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "OVE3RCHROME - Alternative LUT", ModId.From(6579),
            FileId.From(39289), Hash.From(0xC9CF6070A596BFDA), new[]
            {
                "mods/OVE3RCHROME - Default EACO Diverse Weather/archives/OVE3RCHROME - Default EACO Diverse Weather.archive",
                "mods/OVE3RCHROME - Default EACO Diverse Weather/info.json"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Hair BUNS PACK", ModId.From(6072), FileId.From(31979),
            Hash.From(0xAFEABDAF2B38E408), new[]
            {
                "archive/pc/mod/#WINGDEER_FemV_Hair_ALEXA_NO37.archive",
                "archive/pc/mod/#WINGDEER_FemV_HAIR_BunsBunsBuns_NO28.archive",
                "archive/pc/mod/#WINGDEER_FemV_HAIR_CINDY_NO35.archive",
                "archive/pc/mod/#WINGDEER_FemV_HAIR_RUTHsHalfBun1.2_NO1.archive",
                "archive/pc/mod/#WINGDEER_FemV_HAIR_RUTHsHalfBun3.2_NO1.archive",
                "archive/pc/mod/#WINGDEER_FemV_lilbun_NO33.archive",
                "archive/pc/mod/WINGDEER_FemV_bunClaudetteBangs_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunClaudetteBangs_NOchopstick_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunNOstrands_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunNOstrands_NOchopsticks_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunwEveBangs_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunwEveBangs_NOchopstick_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunwStrands_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_bunwStrands_NOchopstick_no37.archive",
                "archive/pc/mod/WINGDEER_FemV_ChopsticBun_no28.archive"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Cyberscript Core", ModId.From(6475), FileId.From(39313),
            Hash.From(0x0A18B74B0A78188F), new[]
            {
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/character/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/choice/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/circuit/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/codex/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/event/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_afterlife.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_aldecaldos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_arasaka.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_delamain.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_kangtao.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_maxtac.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_mox.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_ncpd.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_scavengers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_sixthstreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_trauma.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_tygerclaws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_voodooboys.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/faction_wraiths.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/faction/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_captain.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_CoachFred.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_Dakota.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_Dino.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_jean.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_kangtao.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_maxtac.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_meredith.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_michiko.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_Nash.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_padre.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_Patricia.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_Regina.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_Rita Mox.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_rogue.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_traumateam.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/fixer_wakako.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/fixer/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/functions/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/help/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/housing_template/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/housing/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/districtWidget.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/factiontitle.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/factionwidget.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/posWidget.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/roomwidget.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/hud/timerwidget.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/interact/open_datapack_group_ui.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/interact/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/interfaces/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/lang/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/mission/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/node/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/npc/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/path/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/phone_dialog/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/place/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/place/vapart.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/poi/Car_chase_POis.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/poi/Car_crash_Pois.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/poi/CAR_PATROLLINGs.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/poi/Crowd_POIs.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/poi/Crowds_Service.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/poi/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/radio/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/scene/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/setting/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/shard/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/sounds/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/texture/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/assets/webpage/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/datapack/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/db.sqlite3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/desc.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/init.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/actiontemplate.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/actiontemplate.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/CharacterEntryLibrary.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/CharacterLibrary.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/workspot/cyberscript_workspot_base.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/workspot/cyberscript_workspot_custom_base.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/workspot/cyberscript_workspot_head.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/workspot/cyberscript_workspot_items.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/anims/workspot/cyberscript_workspot_specialnpc.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/appearances.csv",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_6thStreet_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_6thStreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Aldecaldos_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Aldecaldos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Animals_e3.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Animals_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Arasaka_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Arasaka.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_01_Drug_Producers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_03_Kendachi.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_05_Kendachi.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_06_6thstreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_10_Cytech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_11_6thstreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_arr_12_Chasers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Border_guards_ow.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_border_guards.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_CCL_GangA.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_CCL_GangB.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Child_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Civilian.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_claire.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_cpo_friendly_hostile_02.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_cpo_hostile_01.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_cpz_01_NCART.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Criminal_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Criminal.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_cvi_02_Animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Cyberninja_Oda.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Dakota.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_hey_gle_05_police.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_hey_gle_05_valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_std_rcr_06_6th_street.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_std_rcr_06_scavs.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_wat_lch_11_police.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_wbr_hil_06_6th_street.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_wbr_hil_06_arasaka.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_wbr_jpn_05_police.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_de_wbr_jpn_05_tyger_claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_DeadMaelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_dtn_02_Animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_dtn_03_animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_dtn_04_Biotechnica.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_dtn_05_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Emmerick.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_EnemyHostile.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_EnemyNautral.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Fingers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Follower.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Friendly.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_gle_01_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_gle_01_Tucker.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_gle_03_Security.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_gle_04_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_gle_05_ElGallo.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_gle_06_6thStreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Grayson.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Guard.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_GuardPissedOff.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Haru.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_hil_01_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_hil_06_6thstreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_hil_07_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_hil_101_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Hostile.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_02_big_pete.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_02_Wraiths.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_03_Wraiths.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_04_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_05_Miltech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_06_Tanner.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_06_Wraiths.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_07_Maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_08_Wraiths.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_09_Jason.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_101_Miltech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_11_Landfill_Guards.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ina_11_scavs.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Jackie.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_01_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_02_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_03_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_05_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_09_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_12_Guard.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_12_technician.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_jpn_12_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Judy.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_01_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_03_Cpl_Hare.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_04_Akulov.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_04_Nadezhda.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_04_Receptionist.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_05_Scavengers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_06_Animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_07_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_08_DaveHamill.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_08_TygerClaws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_102_Cargo.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_103_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_104_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_106_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_kab_107_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Kangtao_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Kangtao.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_lch_01_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_lch_03_roh.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_lch_03_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_lch_06_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ma_pac_cvi_08_psycho.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ma_wat_lch_07_maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_ma_wat_lch_07_police.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Maelstrom_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Maiko.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Max_Border_guards.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Militech_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq005_police.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq009_homeless.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_MQ010_Barry.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_greencloud.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_jogger.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_nomads.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_paparazzi.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_prophet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq026_smuggler.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq029_james.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq030_cyberpsycho.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq030_jinguji_bodyguard.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq030_max_tac.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq031_6th.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq031_civilians.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq031_combat_drone.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_mq035_tyger_claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Neutral.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_01_Lizzies.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_01_Psycho.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_02_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_03_Turrets.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_03_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_04_Maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_05_Maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_07_AaronMcCarlson.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_07_maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_101_Maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_102_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_nid_12_Mercenaries.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Panam.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Placide.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Player.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Police.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_PoliceHostile.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_PreventionGlobal.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_PreventionKabuki.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q000_arasaka_agents.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q000_border_patrol.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q000_roadhouse_town_defenders.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q001_scavengers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q003_Dexter.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q003_maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q003_militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q005_arasaka_hotel.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q101_Arasakas.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q103_6th_Street.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q103_Raffen_Shiv.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q104_Neutral_Petrochem.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q104_Petrochem_Operators.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q105_04d_gang_m_01.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q105_04d_gang_m_02t.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q105_receptionist.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q105_scavengers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q105_tyger_claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q105_tyger_goons.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q108_arasaka_lift.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q108_arasaka.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q108_backalley_thugs.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q110_mall_animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q110_netwatch_agent.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q110_voodoo_boys.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Q112_TroysGoons.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_q203_arasaka.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rcr_01_Community.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rcr_02_Security.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rcr_03_6thstreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rcr_03_turrets.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rcr_04_Gangers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rcr_05_Cyberpsycho.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rey_01_Valentinos_ground_floor.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rey_01_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rey_02_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rey_06_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rey_08_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_rey_09_Tyger_Claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_roadblocks_prolog_Arasaka.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Rogue.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Roxanne.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Royce.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Santiago.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Scavenger_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Scavenger.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Security_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SecurityHostile.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Sobchak.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_spr_01_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_spr_03_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_spr_06_Animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_spr_08_Militech.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_spr_08_NonCombat.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq004_Raffen_Shiv.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq006_tyger_claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq011_animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq011_kerry_bots.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq011_maelstrom_doors.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq011_maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq011_nancy.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq011_patricia.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq012_6th_street.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq012_tyger_claws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ017_Nightclub_Guards.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ018_6thStreet.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ018_Bernie.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ018_MaxTac.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ018_Melissa.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ018_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_SQ022_Megablock_Gangers.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq023_joshua.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq023_vasquez.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq024_race_team_1.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq024_race_team_2.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq024_race_team_3.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq024_race_team_4.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq024_race_team_5.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq025_delamain_drones_divergent.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq025_delamain_drones.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq025_netwatch_fake.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq025_netwatch_real.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq026_dollhouse_security.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq026_hiromi_security.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq026_hiromi.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq026_maintenance_worker.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sq031_maelstrom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_sts_nid_06_enemy.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Takemura.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Tom.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_TraumaTeam.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_TygerClaws_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_TygerClaws.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Valentinos_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Valentinos.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Vendor_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_VoodooBoys_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_VoodooBoys.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Weyland.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Wraiths_OW.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Wraiths.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_wwd_05_Animals.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/Group_Yorinobu_Guards.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/attitudegroup/QuickHack_Madness.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/bounty_transgression.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/CharacterTable.xlsx",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/ChoiceIcons.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/codex.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/contexttemplate.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/corpolist.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/districts.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/entities.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/entitieshash.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/facial.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/fact.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/factdump.txt",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/fasttravelmarkref.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/gameaffinity.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/gamesounds.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/getItems.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/imageGlossary.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/inputUserMappings.xml",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/npcstar.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/settings.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/startaffinity.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/statuteffect.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/theme.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/triggertemplate.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/triggertemplate.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/vehicles.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/data/workspot.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/AIControl.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/amm_component.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/amm_entities.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/attachment-slots.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/attributes.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/CorruptNCPDLang.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/cpstyling_default.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/cpstyling.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/crafting-components.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/Cron.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/equipment-areas.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/EventProxy.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/GameHUD.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/GameSession.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/GameSettings.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/GameUI.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/ImGuiExtension.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/interactionUI.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/json.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/perks-by-alias.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/perks.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/QuestJournalUI.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/QuestManager.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/QuestTrackerUI.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/Ref.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/skills.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/styles.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/TargetingHelper.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/tweakdb-ids.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/tweakdb-meta.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/UIButton.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/UIPopupsManager.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/external/UIScroller.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/lang/default.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/api.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/av.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/core.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/db.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/editor.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/gang.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/housing.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/inventory.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/loader.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/location.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/modpack.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/npc.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/observer_call.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/observer_function.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/place.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/quest.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/relation.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/saves.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/scripting.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/see.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/shop.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/sound.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/ui.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/utils.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/mod/modules/var.lua",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/user/cache/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/user/editor_output/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/user/sessions/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/cyberscript/user/settings/placeholder",
                "bin/x64/plugins/cyber_engine_tweaks/mods/zzzzzz_cyberscript_amm_compatibility/init.lua"
            }.Select(p => new GamePath(LocationId.Game, p))
        },
        new object[]
        {
            "Een Glish Radio", ModId.From(6172), FileId.From(39296),
            Hash.From(0x774BB4AB62B00F50), new[]
            {
                "archive/pc/mod/Een Glish Radio.archive",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Best Days.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Beta Data.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Big Diamonds.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Big Sur (feat. DesktopDavid).mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Carry The Game.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Cartridge.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Casita.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Dewey Decimals.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Dreams.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Eekonomics.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Good Day.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Google Sheets.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Guests Came Over.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/I Do Not Exist.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Jet Set Ratio.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Leave.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Lock Down.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/metadata.json",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Overflow (feat. Tyfty).mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Payphones.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Rap Game Bob Ross.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/See Me.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/so what's up.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Thats Facts.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Then I Found You.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Thrill.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Timmy Turner, Pt. 2.mp3",
                "bin/x64/plugins/cyber_engine_tweaks/mods/radioExt/radios/Een Glish/Unprepared.mp3",
            }.Select(p => new GamePath(LocationId.Game, p))
        }
    };
}
