comment:                  # this is a top-level key
  status:
    project:
      default:
        threshold: 0.01 # 1%
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  # prevent codecov from writing a comment before n builds have finished
  # this number should be the number of operating systems tested
  after_n_builds: 2 
