using MemoryPack;

namespace NexusMods.Networking.Downloaders.Tasks.State;

/// <summary>
/// State specific to <see cref="HttpDownloadTask"/> suspend.
/// </summary>
[MemoryPackable(GenerateType.VersionTolerant)]
// ReSharper disable once PartialTypeWithSinglePart
public partial struct HttpDownloadState
{
    /// <summary>
    /// URL from which the item is to be downloaded.
    /// </summary>
    [MemoryPackOrder(0)]
    public string Url { get; init; }
    
    #region Autogenerated
    public bool Equals(HttpDownloadState other) => Url == other.Url;
    public override bool Equals(object? obj) => obj is HttpDownloadState other && Equals(other);
    public override int GetHashCode() => Url.GetHashCode();
    #endregion
}
