using MemoryPack;

namespace NexusMods.Networking.Downloaders.Tasks.State;

/// <summary>
/// State specific to <see cref="NxmDownloadTask"/> suspend.
/// </summary>
[MemoryPackable(GenerateType.VersionTolerant)]
public partial class NxmDownloadState
{
    /// <summary>
    /// Converts to NXMUrl.
    /// </summary>
    [MemoryPackOrder(0)]
    public string Query { get; init; } = null!;
    
    #region Autogenerated
    protected bool Equals(NxmDownloadState other) => Query == other.Query;

    public override bool Equals(object? obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((NxmDownloadState)obj);
    }

    public override int GetHashCode() => Query.GetHashCode();
    #endregion
}
