using NexusMods.DataModel.Loadouts.ModFiles;
using NexusMods.Hashing.xxHash64;
using NexusMods.Paths;

namespace NexusMods.DataModel.Loadouts;

/// <summary>
/// Represents a mod file that is generated by some source, instead of being a file from an archive.
/// </summary>
public abstract record class AGeneratedFile : AStaticModFile
{
    /// <summary>
    /// Generate the contents of the file, writing it to the given stream.
    /// </summary>
    /// <param name="stream"></param>
    /// <param name="loadout"></param>
    /// <param name="flattenedList"></param>
    /// <param name="ct"></param>
    /// <returns></returns>
    public abstract Task GenerateAsync(Stream stream, Loadout loadout, IReadOnlyCollection<(AModFile File, Mod Mod)> flattenedList, CancellationToken ct = default);

    public abstract Task<(Size Size, Hash Hash)> GetMetaData(Loadout loadout, IReadOnlyCollection<(AModFile File, Mod Mod)> flattenedList, CancellationToken ct = default);


}
