
// This file is automatically generated by the T4 template: VerbRegistration.tt
// do not edit this file directly
using Microsoft.Extensions.DependencyInjection;
namespace NexusMods.CLI;
using NexusMods.CLI.Verbs;

public static class CommandLineBuilderExtensions{ 

public static void AddCLIVerbs(this IServiceCollection services) {
CommandLineBuilder.RegisterCommand<HashFolder>(HashFolder.Definition, c => ((HashFolder)c).Run);
services.AddScoped<HashFolder>();
CommandLineBuilder.RegisterCommand<ListGames>(ListGames.Definition, c => ((ListGames)c).Run);
services.AddScoped<ListGames>();
CommandLineBuilder.RegisterCommand<ListManagedGames>(ListManagedGames.Definition, c => ((ListManagedGames)c).Run);
services.AddScoped<ListManagedGames>();
CommandLineBuilder.RegisterCommand<ListModContents>(ListModContents.Definition, c => ((ListModContents)c).Run);
services.AddScoped<ListModContents>();
CommandLineBuilder.RegisterCommand<ListMods>(ListMods.Definition, c => ((ListMods)c).Run);
services.AddScoped<ListMods>();
CommandLineBuilder.RegisterCommand<ManageGame>(ManageGame.Definition, c => ((ManageGame)c).Run);
services.AddScoped<ManageGame>();
}
}