//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusMods.Games.AdvancedInstaller.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusMods.Games.AdvancedInstaller.UI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Mod.
        /// </summary>
        public static string AdvancedInstaller_Manual_Mod {
            get {
                return ResourceManager.GetString("AdvancedInstaller_Manual_Mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL FOLDERS.
        /// </summary>
        public static string AllFoldersAreaHeaderText_ALL_FOLDERS {
            get {
                return ResourceManager.GetString("AllFoldersAreaHeaderText_ALL_FOLDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from the full folder structure.
        /// </summary>
        public static string AllFoldersAreaSubHeaderText_Select_from_full {
            get {
                return ResourceManager.GetString("AllFoldersAreaSubHeaderText_Select_from_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelCreateFolderButton_Cancel {
            get {
                return ResourceManager.GetString("CancelCreateFolderButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        public static string CreateFolderButton_Create_new_folder {
            get {
                return ResourceManager.GetString("CreateFolderButton_Create_new_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteCreatedFolderButton_Delete {
            get {
                return ResourceManager.GetString("DeleteCreatedFolderButton_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which files to install from the mod archive on the left..
        /// </summary>
        public static string EmptyPreviewText_Select_files_to_install {
            get {
                return ResourceManager.GetString("EmptyPreviewText_Select_files_to_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are confident this mod is safe, and you know where the files need to be installed, you can attempt an advanced manual install..
        /// </summary>
        public static string ExtraDescriptionTextBlock_If_you_are_confident {
            get {
                return ResourceManager.GetString("ExtraDescriptionTextBlock_If_you_are_confident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All mod files.
        /// </summary>
        public static string FileTree_ALL_MOD_FILES {
            get {
                return ResourceManager.GetString("FileTree_ALL_MOD_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Footer_CANCEL {
            get {
                return ResourceManager.GetString("Footer_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Footer_INSTALL {
            get {
                return ResourceManager.GetString("Footer_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced manual mod installer.
        /// </summary>
        public static string InstallerNameText {
            get {
                return ResourceManager.GetString("InstallerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with no location selected will not be installed..
        /// </summary>
        public static string ModContentSubHeading_Files_with_no {
            get {
                return ResourceManager.GetString("ModContentSubHeading_Files_with_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD CONTENT.
        /// </summary>
        public static string ModContentTitle_MOD_CONTENT {
            get {
                return ResourceManager.GetString("ModContentTitle_MOD_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string NewFilePill_NEW {
            get {
                return ResourceManager.GetString("NewFilePill_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced installer.
        /// </summary>
        public static string OverlayHeaderText_Advanced_Installer {
            get {
                return ResourceManager.GetString("OverlayHeaderText_Advanced_Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DUPE FOLDER.
        /// </summary>
        public static string Pill_DUPE_FOLDER {
            get {
                return ResourceManager.GetString("Pill_DUPE_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOLDER MERGED.
        /// </summary>
        public static string Pill_FOLDER_MERGED {
            get {
                return ResourceManager.GetString("Pill_FOLDER_MERGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALL LOCATION PREVIEW.
        /// </summary>
        public static string PreviewHeader_INSTALL_LOCATION_PREVIEW {
            get {
                return ResourceManager.GetString("PreviewHeader_INSTALL_LOCATION_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files/folders labelled as “New” will be installed/added..
        /// </summary>
        public static string PreviewSubHeading_Files_labelled_as_new {
            get {
                return ResourceManager.GetString("PreviewSubHeading_Files_labelled_as_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveCreatedFolderButton_Save {
            get {
                return ResourceManager.GetString("SaveCreatedFolderButton_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectButton_Select {
            get {
                return ResourceManager.GetString("SelectButton_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        public static string SelectLocationButton_Select_location {
            get {
                return ResourceManager.GetString("SelectLocationButton_Select_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT INSTALL LOCATION.
        /// </summary>
        public static string SelectLocationHeaderText_SELECT_INSTALL_LOCATION {
            get {
                return ResourceManager.GetString("SelectLocationHeaderText_SELECT_INSTALL_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to install the mod file/folder..
        /// </summary>
        public static string SelectLocationSubHeadingText_Select_where_to {
            get {
                return ResourceManager.GetString("SelectLocationSubHeadingText_Select_where_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Mods are usually installed in the following game folders..
        /// </summary>
        public static string SelectLocationViewModel_SuggestedLocationsSubtitle {
            get {
                return ResourceManager.GetString("SelectLocationViewModel_SuggestedLocationsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the files to install and where they should be installed to..
        /// </summary>
        public static string SubHeadingText_Please_select_files {
            get {
                return ResourceManager.GetString("SubHeadingText_Please_select_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUGGESTED.
        /// </summary>
        public static string SuggestedHeaderText_SUGGESTED {
            get {
                return ResourceManager.GetString("SuggestedHeaderText_SUGGESTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All mod files.
        /// </summary>
        public static string TreeEntryView_FileNameTextBlock_All_mod_files {
            get {
                return ResourceManager.GetString("TreeEntryView_FileNameTextBlock_All_mod_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included.
        /// </summary>
        public static string TreeEntryView_IncludedRemoveButtonTextBlock_Included {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludedRemoveButtonTextBlock_Included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included folder.
        /// </summary>
        public static string TreeEntryView_IncludedRemoveButtonTextBlock_Included_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludedRemoveButtonTextBlock_Included_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included with folder.
        /// </summary>
        public static string TreeEntryView_IncludedRemoveButtonTextBlock_Included_with_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludedRemoveButtonTextBlock_Included_with_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include.
        /// </summary>
        public static string TreeEntryView_IncludeTransitionButtonTextBlock_Include {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludeTransitionButtonTextBlock_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include folder.
        /// </summary>
        public static string TreeEntryView_IncludeTransitionButtonTextBlock_Include_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludeTransitionButtonTextBlock_Include_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include with folder.
        /// </summary>
        public static string TreeEntryView_IncludeTransitionButtonTextBlock_Include_with_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludeTransitionButtonTextBlock_Include_with_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string TreeEntryView_InstallRoundedButtonTextBlock_Install {
            get {
                return ResourceManager.GetString("TreeEntryView_InstallRoundedButtonTextBlock_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install all.
        /// </summary>
        public static string TreeEntryView_InstallRoundedButtonTextBlock_Install_all {
            get {
                return ResourceManager.GetString("TreeEntryView_InstallRoundedButtonTextBlock_Install_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install folder.
        /// </summary>
        public static string TreeEntryView_InstallRoundedButtonTextBlock_Install_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_InstallRoundedButtonTextBlock_Install_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mod is structured in an unrecognised way, or contains unrecognised file types, so it cannot be installed automatically..
        /// </summary>
        public static string UnsupportedDescriptionTextBlock_This_mod_is_structured {
            get {
                return ResourceManager.GetString("UnsupportedDescriptionTextBlock_This_mod_is_structured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported mod.
        /// </summary>
        public static string UnsupportedModHeader_Unsupported_mod {
            get {
                return ResourceManager.GetString("UnsupportedModHeader_Unsupported_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Install.
        /// </summary>
        public static string UnsupportedOverlayFooter_ADVANCED_INSTALL {
            get {
                return ResourceManager.GetString("UnsupportedOverlayFooter_ADVANCED_INSTALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UnsupportedOverlayFooter_CLOSE {
            get {
                return ResourceManager.GetString("UnsupportedOverlayFooter_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mod is not supported.
        /// </summary>
        public static string UnsupportedTitleTextBlock_This_mod_is_not_supported {
            get {
                return ResourceManager.GetString("UnsupportedTitleTextBlock_This_mod_is_not_supported", resourceCulture);
            }
        }
    }
}
