//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusMods.Games.AdvancedInstaller.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NexusMods.Games.AdvancedInstaller.UI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Footer_CANCEL {
            get {
                return ResourceManager.GetString("Footer_CANCEL", resourceCulture);
            }
        }
        
        public static string Footer_INSTALL {
            get {
                return ResourceManager.GetString("Footer_INSTALL", resourceCulture);
            }
        }
        
        public static string OverlayHeaderText_Advanced_Installer {
            get {
                return ResourceManager.GetString("OverlayHeaderText_Advanced_Installer", resourceCulture);
            }
        }
        
        public static string InstallerNameText {
            get {
                return ResourceManager.GetString("InstallerNameText", resourceCulture);
            }
        }
        
        public static string SubHeadingText_Please_select_files {
            get {
                return ResourceManager.GetString("SubHeadingText_Please_select_files", resourceCulture);
            }
        }
        
        public static string ModContentTitle_MOD_CONTENT {
            get {
                return ResourceManager.GetString("ModContentTitle_MOD_CONTENT", resourceCulture);
            }
        }
        
        public static string ModContentSubHeading_Files_with_no {
            get {
                return ResourceManager.GetString("ModContentSubHeading_Files_with_no", resourceCulture);
            }
        }
        
        public static string CreateFolderButton_Create_new_folder {
            get {
                return ResourceManager.GetString("CreateFolderButton_Create_new_folder", resourceCulture);
            }
        }
        
        public static string NewFilePill_NEW {
            get {
                return ResourceManager.GetString("NewFilePill_NEW", resourceCulture);
            }
        }
        
        public static string Pill_DUPE_FOLDER {
            get {
                return ResourceManager.GetString("Pill_DUPE_FOLDER", resourceCulture);
            }
        }
        
        public static string Pill_FOLDER_MERGED {
            get {
                return ResourceManager.GetString("Pill_FOLDER_MERGED", resourceCulture);
            }
        }
        
        public static string SelectLocationButton_Select_location {
            get {
                return ResourceManager.GetString("SelectLocationButton_Select_location", resourceCulture);
            }
        }
        
        public static string SelectButton_Select {
            get {
                return ResourceManager.GetString("SelectButton_Select", resourceCulture);
            }
        }
        
        public static string DeleteCreatedFolderButton_Delete {
            get {
                return ResourceManager.GetString("DeleteCreatedFolderButton_Delete", resourceCulture);
            }
        }
        
        public static string CancelCreateFolderButton_Cancel {
            get {
                return ResourceManager.GetString("CancelCreateFolderButton_Cancel", resourceCulture);
            }
        }
        
        public static string SaveCreatedFolderButton_Save {
            get {
                return ResourceManager.GetString("SaveCreatedFolderButton_Save", resourceCulture);
            }
        }
        
        public static string EmptyPreviewText_Select_files_to_install {
            get {
                return ResourceManager.GetString("EmptyPreviewText_Select_files_to_install", resourceCulture);
            }
        }
        
        public static string SelectLocationHeaderText_SELECT_INSTALL_LOCATION {
            get {
                return ResourceManager.GetString("SelectLocationHeaderText_SELECT_INSTALL_LOCATION", resourceCulture);
            }
        }
        
        public static string SelectLocationSubHeadingText_Select_where_to {
            get {
                return ResourceManager.GetString("SelectLocationSubHeadingText_Select_where_to", resourceCulture);
            }
        }
        
        public static string SuggestedHeaderText_SUGGESTED {
            get {
                return ResourceManager.GetString("SuggestedHeaderText_SUGGESTED", resourceCulture);
            }
        }
        
        public static string AllFoldersAreaHeaderText_ALL_FOLDERS {
            get {
                return ResourceManager.GetString("AllFoldersAreaHeaderText_ALL_FOLDERS", resourceCulture);
            }
        }
        
        public static string AllFoldersAreaSubHeaderText_Select_from_full {
            get {
                return ResourceManager.GetString("AllFoldersAreaSubHeaderText_Select_from_full", resourceCulture);
            }
        }
        
        public static string FileTree_ALL_MOD_FILES {
            get {
                return ResourceManager.GetString("FileTree_ALL_MOD_FILES", resourceCulture);
            }
        }
        
        public static string PreviewHeader_INSTALL_LOCATION_PREVIEW {
            get {
                return ResourceManager.GetString("PreviewHeader_INSTALL_LOCATION_PREVIEW", resourceCulture);
            }
        }
        
        public static string PreviewSubHeading_Files_labelled_as_new {
            get {
                return ResourceManager.GetString("PreviewSubHeading_Files_labelled_as_new", resourceCulture);
            }
        }
        
        public static string UnsupportedModHeader_Unsupported_mod {
            get {
                return ResourceManager.GetString("UnsupportedModHeader_Unsupported_mod", resourceCulture);
            }
        }
        
        public static string UnsupportedTitleTextBlock_This_mod_is_not_supported {
            get {
                return ResourceManager.GetString("UnsupportedTitleTextBlock_This_mod_is_not_supported", resourceCulture);
            }
        }
        
        public static string UnsupportedDescriptionTextBlock_This_mod_is_structured {
            get {
                return ResourceManager.GetString("UnsupportedDescriptionTextBlock_This_mod_is_structured", resourceCulture);
            }
        }
        
        public static string ExtraDescriptionTextBlock_If_you_are_confident {
            get {
                return ResourceManager.GetString("ExtraDescriptionTextBlock_If_you_are_confident", resourceCulture);
            }
        }
        
        public static string UnsupportedOverlayFooter_ADVANCED_INSTALL {
            get {
                return ResourceManager.GetString("UnsupportedOverlayFooter_ADVANCED_INSTALL", resourceCulture);
            }
        }
        
        public static string UnsupportedOverlayFooter_CLOSE {
            get {
                return ResourceManager.GetString("UnsupportedOverlayFooter_CLOSE", resourceCulture);
            }
        }
        
        public static string TreeEntryView_FileNameTextBlock_All_mod_files {
            get {
                return ResourceManager.GetString("TreeEntryView_FileNameTextBlock_All_mod_files", resourceCulture);
            }
        }
        
        public static string TreeEntryView_InstallRoundedButtonTextBlock_Install_all {
            get {
                return ResourceManager.GetString("TreeEntryView_InstallRoundedButtonTextBlock_Install_all", resourceCulture);
            }
        }
        
        public static string TreeEntryView_InstallRoundedButtonTextBlock_Install_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_InstallRoundedButtonTextBlock_Install_folder", resourceCulture);
            }
        }
        
        public static string TreeEntryView_InstallRoundedButtonTextBlock_Install {
            get {
                return ResourceManager.GetString("TreeEntryView_InstallRoundedButtonTextBlock_Install", resourceCulture);
            }
        }
        
        public static string TreeEntryView_IncludeTransitionButtonTextBlock_Include_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludeTransitionButtonTextBlock_Include_folder", resourceCulture);
            }
        }
        
        public static string TreeEntryView_IncludeTransitionButtonTextBlock_Include_with_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludeTransitionButtonTextBlock_Include_with_folder", resourceCulture);
            }
        }
        
        public static string TreeEntryView_IncludedRemoveButtonTextBlock_Included_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludedRemoveButtonTextBlock_Included_folder", resourceCulture);
            }
        }
        
        public static string TreeEntryView_IncludedRemoveButtonTextBlock_Included_with_folder {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludedRemoveButtonTextBlock_Included_with_folder", resourceCulture);
            }
        }
        
        public static string TreeEntryView_IncludeTransitionButtonTextBlock_Include {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludeTransitionButtonTextBlock_Include", resourceCulture);
            }
        }
        
        public static string TreeEntryView_IncludedRemoveButtonTextBlock_Included {
            get {
                return ResourceManager.GetString("TreeEntryView_IncludedRemoveButtonTextBlock_Included", resourceCulture);
            }
        }
        
        public static string AdvancedInstaller_Manual_Mod {
            get {
                return ResourceManager.GetString("AdvancedInstaller_Manual_Mod", resourceCulture);
            }
        }
        
        public static string SelectLocationViewModel_SuggestedLocationsSubtitle {
            get {
                return ResourceManager.GetString("SelectLocationViewModel_SuggestedLocationsSubtitle", resourceCulture);
            }
        }
    }
}
