using System.Collections.Frozen;
using NexusMods.MnemonicDB.Abstractions;

namespace NexusMods.Abstractions.MnemonicDB.Analyzers;

/// <summary>
/// An analyzer that can be used to analyze changes in a tree. Whenever an entity is updated that
/// modifies an entity, if that entity contains any attributes that are references to other entities, those
/// parent entities are also considered to be modified and included in the updated set, recursively.
/// </summary>
public interface ITreeAnalyzer
{
    /// <summary>
    /// A stream of updates that are generated by this analyzer
    /// </summary>
    public IObservable<TreeUpdate> Updates { get; }
    
    /// <summary>
    /// The connection that this analyzer is attached to
    /// </summary>
    public IConnection Connection { get; }
}

/// <summary>
/// A tuple combining the database and the set of entities that have been updated within that database
/// revision.
/// </summary>
public record struct TreeUpdate(IDb Db, FrozenSet<EntityId> Updated);
