name: Report a missing game
description: 'Use this form to report when the app fails to locate a supported game. '
title: 'Game Not Found'
labels:
  - 'Epic: Game Support'
  - user raised
body:
  - type: markdown
    attributes:
      value: >-
        Please remember that the Nexus Mods app is still in development and
        supports a limited number of games. 


        ## [See all supported games
        here](https://nexus-mods.github.io/NexusMods.App/users/games/)


        Check out [the
        roadmap](https://trello.com/b/gPzMuIr3/nexus-mods-app-roadmap) to see
        the upcoming games.
  - type: checkboxes
    id: confirm-supported
    attributes:
      label: Supported Game Check
      description: >-
        I confirm that I have checked the [supported
        games](https://nexus-mods.github.io/NexusMods.App/users/games/), and the
        game I am reporting is listed as supported but has not been found by the
        app.
      options:
        - label: 'Yes'
          required: true
  - type: dropdown
    id: game
    attributes:
      label: Game
      description: >-
        Which supported game did the app fail to find?
        **If your game is not listed, it isn't supported yet.**
      options:
        - Stardew Valley
        - Cyberpunk 2077
        - Baldur's Gate 3
        - "Mount & Blade II: Bannerlord"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you playing on?
      options:
        - Windows
        - Steam Deck
        - Linux
        - macOS
    validations:
      required: true
  - type: input
    id: linux-distro
    attributes:
      label: Linux Distribution
      description: >-
        If you are using Linux, please specify your distribution (e.g. Ubuntu,
        Fedora, Arch).
      placeholder: e.g. Ubuntu 22.04
  - type: dropdown
    id: store
    attributes:
      label: Game Launcher
      description: Which game store/launcher is the game installed with?
      options:
        - Steam
        - GOG Galaxy
        - Epic Games Launcher
        - Xbox Game Pass/Microsoft Store
        - Heroic Games Launcher (GOG)
        - Heroic Games Launcher (Epic Games)
        - Lutris
        # - Rockstar Games Launcher
        # - Amazon Games
        # - Ubisoft Connect
        # - EA Play
        # - WeGame
        - Manually Installed
        # - Other
    validations:
      required: true
  - type: textarea
    id: log-files
    attributes:
      label: Attach Log Files
      description: >-
        Please attach your logs. If you are having issues finding your log
        files, see [this
        guide](https://nexus-mods.github.io/NexusMods.App/users/faq/LogFiles/).
    validations:
      required: true
