//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusMods.App.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NexusMods.App.UI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Newsfeed {
            get {
                return ResourceManager.GetString("Newsfeed", resourceCulture);
            }
        }
        
        public static string MyGames {
            get {
                return ResourceManager.GetString("MyGames", resourceCulture);
            }
        }
        
        public static string BrowseGames {
            get {
                return ResourceManager.GetString("BrowseGames", resourceCulture);
            }
        }
        
        public static string MetricsOptIn_ALLOW {
            get {
                return ResourceManager.GetString("MetricsOptIn_ALLOW", resourceCulture);
            }
        }
        
        public static string MetricsOptIn_DENY {
            get {
                return ResourceManager.GetString("MetricsOptIn_DENY", resourceCulture);
            }
        }
        
        public static string MetricsOptIn_OverlayTitle {
            get {
                return ResourceManager.GetString("MetricsOptIn_OverlayTitle", resourceCulture);
            }
        }
        
        public static string MetricsOptIn_MoreInfoAboutTheDataWeTrack {
            get {
                return ResourceManager.GetString("MetricsOptIn_MoreInfoAboutTheDataWeTrack", resourceCulture);
            }
        }
        
        public static string MetricsOptIn_MainMessage {
            get {
                return ResourceManager.GetString("MetricsOptIn_MainMessage", resourceCulture);
            }
        }
        
        public static string Updater_UPDATE {
            get {
                return ResourceManager.GetString("Updater_UPDATE", resourceCulture);
            }
        }
        
        public static string Updater_UpdateAvailable {
            get {
                return ResourceManager.GetString("Updater_UpdateAvailable", resourceCulture);
            }
        }
        
        public static string Updater_GenericMessage {
            get {
                return ResourceManager.GetString("Updater_GenericMessage", resourceCulture);
            }
        }
        
        public static string Updater_UsePackageManager {
            get {
                return ResourceManager.GetString("Updater_UsePackageManager", resourceCulture);
            }
        }
        
        public static string Updater_UseInnoSetup {
            get {
                return ResourceManager.GetString("Updater_UseInnoSetup", resourceCulture);
            }
        }
        
        public static string Updater_UseFlatpak {
            get {
                return ResourceManager.GetString("Updater_UseFlatpak", resourceCulture);
            }
        }
        
        public static string LoadoutGridView_AddMod_FilePicker_Title {
            get {
                return ResourceManager.GetString("LoadoutGridView_AddMod_FilePicker_Title", resourceCulture);
            }
        }
        
        public static string LoadoutGridView_AddMod_FileType_Archive {
            get {
                return ResourceManager.GetString("LoadoutGridView_AddMod_FileType_Archive", resourceCulture);
            }
        }
        
        public static string DownloadTaskViewModel_Version_Unknown {
            get {
                return ResourceManager.GetString("DownloadTaskViewModel_Version_Unknown", resourceCulture);
            }
        }
        
        public static string DownloadTaskViewModel_Field_Unknown {
            get {
                return ResourceManager.GetString("DownloadTaskViewModel_Field_Unknown", resourceCulture);
            }
        }
        
        public static string MessageBox_Button_Yes {
            get {
                return ResourceManager.GetString("MessageBox_Button_Yes", resourceCulture);
            }
        }
        
        public static string MessageBox_Button_No {
            get {
                return ResourceManager.GetString("MessageBox_Button_No", resourceCulture);
            }
        }
        
        public static string MessageBox_Button_Ok {
            get {
                return ResourceManager.GetString("MessageBox_Button_Ok", resourceCulture);
            }
        }
        
        public static string CancelDownloadOverlayView_Description_download_will_be_cancelled {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Description_download_will_be_cancelled", resourceCulture);
            }
        }
        
        public static string CancelDownloadOverlayView_Title {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Title", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_NAME {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_NAME", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_VERSION {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_VERSION", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_CATEGORY {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_CATEGORY", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_INSTALLED {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_INSTALLED", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_MOD_NAME {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_MOD_NAME", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_GAME {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_GAME", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_SIZE {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_SIZE", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_STATUS {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_STATUS", resourceCulture);
            }
        }
        
        public static string LaunchButtonViewModel_LaunchGame_RUNNING {
            get {
                return ResourceManager.GetString("LaunchButtonViewModel_LaunchGame_RUNNING", resourceCulture);
            }
        }
        
        public static string LaunchButtonViewModel_LaunchGame_LAUNCH {
            get {
                return ResourceManager.GetString("LaunchButtonViewModel_LaunchGame_LAUNCH", resourceCulture);
            }
        }
        
        public static string LaunchButtonViewModel_LaunchGame_ToolTip {
            get {
                return ResourceManager.GetString("LaunchButtonViewModel_LaunchGame_ToolTip", resourceCulture);
            }
        }
        
        public static string StringFormatters__SecondsRemaining_secs {
            get {
                return ResourceManager.GetString("StringFormatters__SecondsRemaining_secs", resourceCulture);
            }
        }
        
        public static string StringFormatters__MinutesRemaining_mins {
            get {
                return ResourceManager.GetString("StringFormatters__MinutesRemaining_mins", resourceCulture);
            }
        }
        
        public static string StringFormatters__HoursRemaining__hours {
            get {
                return ResourceManager.GetString("StringFormatters__HoursRemaining__hours", resourceCulture);
            }
        }
        
        public static string StringFormatters__In_progress__numDownloads {
            get {
                return ResourceManager.GetString("StringFormatters__In_progress__numDownloads", resourceCulture);
            }
        }
        
        public static string DownloadStatus_Idle {
            get {
                return ResourceManager.GetString("DownloadStatus_Idle", resourceCulture);
            }
        }
        
        public static string DownloadStatus_Progress {
            get {
                return ResourceManager.GetString("DownloadStatus_Progress", resourceCulture);
            }
        }
        
        public static string Nexus_Premium_Status__Premium {
            get {
                return ResourceManager.GetString("Nexus_Premium_Status__Premium", resourceCulture);
            }
        }
        
        public static string Nexus_Premium_Status__Free {
            get {
                return ResourceManager.GetString("Nexus_Premium_Status__Free", resourceCulture);
            }
        }
        
        public static string Nexus_Premium_Status__Supporter {
            get {
                return ResourceManager.GetString("Nexus_Premium_Status__Supporter", resourceCulture);
            }
        }
        
        public static string SearchBox__Search {
            get {
                return ResourceManager.GetString("SearchBox__Search", resourceCulture);
            }
        }
        
        public static string TopBarActions__LOG_IN {
            get {
                return ResourceManager.GetString("TopBarActions__LOG_IN", resourceCulture);
            }
        }
        
        public static string GameWidget__Add_game {
            get {
                return ResourceManager.GetString("GameWidget__Add_game", resourceCulture);
            }
        }
        
        public static string DownloadsView__DOWNLOADS {
            get {
                return ResourceManager.GetString("DownloadsView__DOWNLOADS", resourceCulture);
            }
        }
        
        public static string DownloadsView__In_Progress {
            get {
                return ResourceManager.GetString("DownloadsView__In_Progress", resourceCulture);
            }
        }
        
        public static string DownloadsView__Completed {
            get {
                return ResourceManager.GetString("DownloadsView__Completed", resourceCulture);
            }
        }
        
        public static string DownloadsView__Download_history {
            get {
                return ResourceManager.GetString("DownloadsView__Download_history", resourceCulture);
            }
        }
        
        public static string DownloadsView_UnderDevelopment {
            get {
                return ResourceManager.GetString("DownloadsView_UnderDevelopment", resourceCulture);
            }
        }
        
        public static string NexusLoginOverlayView__Please_Click_Authorize {
            get {
                return ResourceManager.GetString("NexusLoginOverlayView__Please_Click_Authorize", resourceCulture);
            }
        }
        
        public static string NexusLoginOverlayView__BROWSER_DIDNT_OPEN {
            get {
                return ResourceManager.GetString("NexusLoginOverlayView__BROWSER_DIDNT_OPEN", resourceCulture);
            }
        }
        
        public static string NexusLoginOverlayView_Please_copy_url {
            get {
                return ResourceManager.GetString("NexusLoginOverlayView_Please_copy_url", resourceCulture);
            }
        }
        
        public static string DownloadCompleted_COMPLETED {
            get {
                return ResourceManager.GetString("DownloadCompleted_COMPLETED", resourceCulture);
            }
        }
        
        public static string DownloadCompleted_Clear_All {
            get {
                return ResourceManager.GetString("DownloadCompleted_Clear_All", resourceCulture);
            }
        }
        
        public static string DownloadHistoryView__HISTORY {
            get {
                return ResourceManager.GetString("DownloadHistoryView__HISTORY", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__IN_PROGRESS {
            get {
                return ResourceManager.GetString("DownloadInProgressView__IN_PROGRESS", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Cancel {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Cancel", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Pause {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Pause", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Pause_All {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Pause_All", resourceCulture);
            }
        }
        
        public static string InProgressTitleTextBlock {
            get {
                return ResourceManager.GetString("InProgressTitleTextBlock", resourceCulture);
            }
        }
        
        public static string BoldMinutesRemainingTextBlock {
            get {
                return ResourceManager.GetString("BoldMinutesRemainingTextBlock", resourceCulture);
            }
        }
        
        public static string MinutesRemainingTextBlock {
            get {
                return ResourceManager.GetString("MinutesRemainingTextBlock", resourceCulture);
            }
        }
        
        public static string InProgressView_InProgressView_Remaining {
            get {
                return ResourceManager.GetString("InProgressView_InProgressView_Remaining", resourceCulture);
            }
        }
        
        public static string HomeView__We_found_games {
            get {
                return ResourceManager.GetString("HomeView__We_found_games", resourceCulture);
            }
        }
        
        public static string HomeView__CANT_SEE_YOUR_GAME {
            get {
                return ResourceManager.GetString("HomeView__CANT_SEE_YOUR_GAME", resourceCulture);
            }
        }
        
        public static string HomeView__BROWSE_ALL_GAMES {
            get {
                return ResourceManager.GetString("HomeView__BROWSE_ALL_GAMES", resourceCulture);
            }
        }
        
        public static string FileOriginPage_DeleteMod {
            get {
                return ResourceManager.GetString("FileOriginPage_DeleteMod", resourceCulture);
            }
        }
        
        public static string FileOriginPage_AddMod {
            get {
                return ResourceManager.GetString("FileOriginPage_AddMod", resourceCulture);
            }
        }
        
        public static string FileOriginPage_AddModAdvanced {
            get {
                return ResourceManager.GetString("FileOriginPage_AddModAdvanced", resourceCulture);
            }
        }
        
        public static string MyGamesView__Ready_to_mod {
            get {
                return ResourceManager.GetString("MyGamesView__Ready_to_mod", resourceCulture);
            }
        }
        
        public static string MyGamesView__Detected_games {
            get {
                return ResourceManager.GetString("MyGamesView__Detected_games", resourceCulture);
            }
        }
        
        public static string MyGamesView__Page_Description {
            get {
                return ResourceManager.GetString("MyGamesView__Page_Description", resourceCulture);
            }
        }
        
        public static string Button_Manage {
            get {
                return ResourceManager.GetString("Button_Manage", resourceCulture);
            }
        }
        
        public static string ProgressBar_ProgressTextFormat__Total_1_0 {
            get {
                return ResourceManager.GetString("ProgressBar_ProgressTextFormat__Total_1_0", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Queued {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Queued", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Paused {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Paused", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Downloading {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Downloading", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Installing {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Installing", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Complete {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Complete", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Analyzing {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Analyzing", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_Text_Queued_0_ {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_Text_Queued_0_", resourceCulture);
            }
        }
        
        public static string PanelTabHeaderViewModel_Title_New_Tab {
            get {
                return ResourceManager.GetString("PanelTabHeaderViewModel_Title_New_Tab", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Resume {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Resume", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Resume_All {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Resume_All", resourceCulture);
            }
        }
        
        public static string CancelDownloadOverlayView_Description__Download {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Description__Download", resourceCulture);
            }
        }
        
        public static string CancelDownloadOverlayView_Description_downloads {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Description_downloads", resourceCulture);
            }
        }
        
        public static string InProgress_NoDownloadsTextBlock {
            get {
                return ResourceManager.GetString("InProgress_NoDownloadsTextBlock", resourceCulture);
            }
        }
        
        public static string SpineDownloadButton_ToolTip {
            get {
                return ResourceManager.GetString("SpineDownloadButton_ToolTip", resourceCulture);
            }
        }
        
        public static string SpineHomeButton_ToolTip_Home {
            get {
                return ResourceManager.GetString("SpineHomeButton_ToolTip_Home", resourceCulture);
            }
        }
        
        public static string LoadoutViewPageTitle {
            get {
                return ResourceManager.GetString("LoadoutViewPageTitle", resourceCulture);
            }
        }
        
        public static string Downloads_WorkspaceTitle {
            get {
                return ResourceManager.GetString("Downloads_WorkspaceTitle", resourceCulture);
            }
        }
        
        public static string HomeWorkspace_Title {
            get {
                return ResourceManager.GetString("HomeWorkspace_Title", resourceCulture);
            }
        }
        
        public static string InProgressDownloadsPage_Title {
            get {
                return ResourceManager.GetString("InProgressDownloadsPage_Title", resourceCulture);
            }
        }
        
        public static string LoadoutGridView__View_Files {
            get {
                return ResourceManager.GetString("LoadoutGridView__View_Files", resourceCulture);
            }
        }
        
        public static string FileTreeNodeView__View {
            get {
                return ResourceManager.GetString("FileTreeNodeView__View", resourceCulture);
            }
        }
        
        public static string ViewModInfoPage_Title {
            get {
                return ResourceManager.GetString("ViewModInfoPage_Title", resourceCulture);
            }
        }
        
        public static string ViewModFilesView_Location {
            get {
                return ResourceManager.GetString("ViewModFilesView_Location", resourceCulture);
            }
        }
        
        public static string ViewModFilesView_Locations {
            get {
                return ResourceManager.GetString("ViewModFilesView_Locations", resourceCulture);
            }
        }
        
        public static string ApplyControlViewModel__ACTIVATE_LOADOUT {
            get {
                return ResourceManager.GetString("ApplyControlViewModel__ACTIVATE_LOADOUT", resourceCulture);
            }
        }
        
        public static string ApplyControlViewModel__ACTIVATE_AND_APPLY {
            get {
                return ResourceManager.GetString("ApplyControlViewModel__ACTIVATE_AND_APPLY", resourceCulture);
            }
        }
        
        public static string ApplyControlViewModel__APPLY {
            get {
                return ResourceManager.GetString("ApplyControlViewModel__APPLY", resourceCulture);
            }
        }
        
        public static string ApplyingControlView__ApplyingText {
            get {
                return ResourceManager.GetString("ApplyingControlView__ApplyingText", resourceCulture);
            }
        }
        
        public static string Helpers_ERROR {
            get {
                return ResourceManager.GetString("Helpers_ERROR", resourceCulture);
            }
        }
        
        public static string ErrorView_Title {
            get {
                return ResourceManager.GetString("ErrorView_Title", resourceCulture);
            }
        }
        
        public static string ErrorView_MissingMod_Description {
            get {
                return ResourceManager.GetString("ErrorView_MissingMod_Description", resourceCulture);
            }
        }
        
        public static string ViewModInfoPage_NotFound_Title {
            get {
                return ResourceManager.GetString("ViewModInfoPage_NotFound_Title", resourceCulture);
            }
        }
        
        public static string ErrorView_MissingMod_Subheader {
            get {
                return ResourceManager.GetString("ErrorView_MissingMod_Subheader", resourceCulture);
            }
        }
        
        public static string DiagnosticDetailsView_SeverityTitle_SUGGESTION {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_SUGGESTION", resourceCulture);
            }
        }
        
        public static string DiagnosticDetailsView_SeverityTitle_WARNING {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_WARNING", resourceCulture);
            }
        }
        
        public static string DiagnosticDetailsView_SeverityTitle_CRITICAL_ERROR {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_CRITICAL_ERROR", resourceCulture);
            }
        }
        
        public static string DiagnosticDetailsView_SeverityTitle_HIDDEN {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_HIDDEN", resourceCulture);
            }
        }
        
        public static string LoadoutLeftMenuViewModel_LoadoutLeftMenuViewModel_Diagnostics {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_LoadoutLeftMenuViewModel_Diagnostics", resourceCulture);
            }
        }
        
        public static string LoadoutLeftMenuViewModel_Diagnostics_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_Diagnostics_ToolTip", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_DiagnosticListView_All {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_All", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_DiagnosticListView_Critical {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_Critical", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_DiagnosticListView_Warnings {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_Warnings", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_DiagnosticListView_Suggestions {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_Suggestions", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_DiagnosticListView_There_are_no_diagnostics {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_There_are_no_diagnostics", resourceCulture);
            }
        }
        
        public static string IngestButtonTextBlock_Text {
            get {
                return ResourceManager.GetString("IngestButtonTextBlock_Text", resourceCulture);
            }
        }
        
        public static string ModFileTreeViewModel_StatusBar_Files__0__1 {
            get {
                return ResourceManager.GetString("ModFileTreeViewModel_StatusBar_Files__0__1", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_File_Count {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_File_Count", resourceCulture);
            }
        }
        
        public static string MyGamesView__NoGamesDetectedText {
            get {
                return ResourceManager.GetString("MyGamesView__NoGamesDetectedText", resourceCulture);
            }
        }
        
        public static string MyGamesView__NoGamesManagedText {
            get {
                return ResourceManager.GetString("MyGamesView__NoGamesManagedText", resourceCulture);
            }
        }
        
        public static string GameWidget__Adding_game {
            get {
                return ResourceManager.GetString("GameWidget__Adding_game", resourceCulture);
            }
        }
        
        public static string GameWidget__View {
            get {
                return ResourceManager.GetString("GameWidget__View", resourceCulture);
            }
        }
        
        public static string GameWidget__RemoveGame_ToolTip {
            get {
                return ResourceManager.GetString("GameWidget__RemoveGame_ToolTip", resourceCulture);
            }
        }
        
        public static string GameWidget__Removing_game {
            get {
                return ResourceManager.GetString("GameWidget__Removing_game", resourceCulture);
            }
        }
        
        public static string ApplyDiff_Refresh {
            get {
                return ResourceManager.GetString("ApplyDiff_Refresh", resourceCulture);
            }
        }
        
        public static string Helpers_GenerateHeader_State {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_State", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Added {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Added", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Modified {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Modified", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Contents_modified {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Contents_modified", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Removed {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Removed", resourceCulture);
            }
        }
        
        public static string DiffTreeViewModel_StatusBar__File_Loadout_Disk {
            get {
                return ResourceManager.GetString("DiffTreeViewModel_StatusBar__File_Loadout_Disk", resourceCulture);
            }
        }
        
        public static string DiffTreeViewModel_StatusBar__Apply_changes {
            get {
                return ResourceManager.GetString("DiffTreeViewModel_StatusBar__Apply_changes", resourceCulture);
            }
        }
        
        public static string DiffTreeViewModel_StatusBar__Data_to_process___0_ {
            get {
                return ResourceManager.GetString("DiffTreeViewModel_StatusBar__Data_to_process___0_", resourceCulture);
            }
        }
        
        public static string ApplyControlView_ViewApplyChanges {
            get {
                return ResourceManager.GetString("ApplyControlView_ViewApplyChanges", resourceCulture);
            }
        }
        
        public static string ApplyDiffViewModel_PageTitle {
            get {
                return ResourceManager.GetString("ApplyDiffViewModel_PageTitle", resourceCulture);
            }
        }
        
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        public static string DialogButton_CANCEL {
            get {
                return ResourceManager.GetString("DialogButton_CANCEL", resourceCulture);
            }
        }
        
        public static string DialogButton_SAVE {
            get {
                return ResourceManager.GetString("DialogButton_SAVE", resourceCulture);
            }
        }
        
        public static string DialogButton_DELETE_MODS {
            get {
                return ResourceManager.GetString("DialogButton_DELETE_MODS", resourceCulture);
            }
        }
        
        public static string SettingEntryView_NeedRestartMessage {
            get {
                return ResourceManager.GetString("SettingEntryView_NeedRestartMessage", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_AddButtonText {
            get {
                return ResourceManager.GetString("FileOriginsPage_AddButtonText", resourceCulture);
            }
        }
        
        public static string DialogButton_Discard {
            get {
                return ResourceManager.GetString("DialogButton_Discard", resourceCulture);
            }
        }
        
        public static string ChangelogPageViewModel_ChangelogPageViewModel_Changelog {
            get {
                return ResourceManager.GetString("ChangelogPageViewModel_ChangelogPageViewModel_Changelog", resourceCulture);
            }
        }
        
        public static string DiagnosticListViewModel_DiagnosticListViewModel_Diagnostics {
            get {
                return ResourceManager.GetString("DiagnosticListViewModel_DiagnosticListViewModel_Diagnostics", resourceCulture);
            }
        }
        
        public static string LibraryPageTitle {
            get {
                return ResourceManager.GetString("LibraryPageTitle", resourceCulture);
            }
        }
        
        public static string LibraryPageTitleToolTip {
            get {
                return ResourceManager.GetString("LibraryPageTitleToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginsPageView_NameHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_NameHeader", resourceCulture);
            }
        }
        
        public static string FileOriginsPageView_VersionHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_VersionHeader", resourceCulture);
            }
        }
        
        public static string FileOriginsPageView_SizeHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_SizeHeader", resourceCulture);
            }
        }
        
        public static string FileOriginsPageView_DownloadedHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_DownloadedHeader", resourceCulture);
            }
        }
        
        public static string FileOriginsPageView_InstalledHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_InstalledHeader", resourceCulture);
            }
        }
        
        public static string FileOriginsPageView_ActionHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_ActionHeader", resourceCulture);
            }
        }
        
        public static string DownloadStatusDesignViewModel_FormatStatus_Cancelled {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Cancelled", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Clear {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Clear", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__Clear_completed {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Clear_completed", resourceCulture);
            }
        }
        
        public static string DownloadInProgressView__View_in_library {
            get {
                return ResourceManager.GetString("DownloadInProgressView__View_in_library", resourceCulture);
            }
        }
        
        public static string LoadoutGridView__Remove {
            get {
                return ResourceManager.GetString("LoadoutGridView__Remove", resourceCulture);
            }
        }
        
        public static string LoginMessageView_BodyTextBlock {
            get {
                return ResourceManager.GetString("LoginMessageView_BodyTextBlock", resourceCulture);
            }
        }
        
        public static string LoginMessageView_Title {
            get {
                return ResourceManager.GetString("LoginMessageView_Title", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_GetMods {
            get {
                return ResourceManager.GetString("FileOriginsPage_GetMods", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_FromDrive {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromDrive", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_FromNexusMods {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromNexusMods", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_ViewButtonText {
            get {
                return ResourceManager.GetString("FileOriginsPage_ViewButtonText", resourceCulture);
            }
        }
        
        public static string AddPanelToolTip {
            get {
                return ResourceManager.GetString("AddPanelToolTip", resourceCulture);
            }
        }
        
        public static string MaxPanelsAddedToolTip {
            get {
                return ResourceManager.GetString("MaxPanelsAddedToolTip", resourceCulture);
            }
        }
        
        public static string Panel_Add_tab_ToolTip {
            get {
                return ResourceManager.GetString("Panel_Add_tab_ToolTip", resourceCulture);
            }
        }
        
        public static string TopBar_MyProfile {
            get {
                return ResourceManager.GetString("TopBar_MyProfile", resourceCulture);
            }
        }
        
        public static string TopBar_SignOut {
            get {
                return ResourceManager.GetString("TopBar_SignOut", resourceCulture);
            }
        }
        
        public static string TopBar_AccountSettings {
            get {
                return ResourceManager.GetString("TopBar_AccountSettings", resourceCulture);
            }
        }
        
        public static string TopBar_GetPremiumMenuItem {
            get {
                return ResourceManager.GetString("TopBar_GetPremiumMenuItem", resourceCulture);
            }
        }
        
        public static string ViewChangelogMenuItem_Header {
            get {
                return ResourceManager.GetString("ViewChangelogMenuItem.Header", resourceCulture);
            }
        }
        
        public static string ViewAppLogsMenuItem_Header {
            get {
                return ResourceManager.GetString("ViewAppLogsMenuItem.Header", resourceCulture);
            }
        }
        
        public static string ShowWelcomeMessageMenuItem_Header {
            get {
                return ResourceManager.GetString("ShowWelcomeMessageMenuItem.Header", resourceCulture);
            }
        }
        
        public static string OpenDiscordMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenDiscordMenuItem.Header", resourceCulture);
            }
        }
        
        public static string OpenGitHubMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenGitHubMenuItem.Header", resourceCulture);
            }
        }
        
        public static string OpenForumsMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenForumsMenuItem.Header", resourceCulture);
            }
        }
        
        public static string OpenStatusPageMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenStatusPageMenuItem.Header", resourceCulture);
            }
        }
        
        public static string NavigationControl_NavigationControl_Open_in_new_tab {
            get {
                return ResourceManager.GetString("NavigationControl_NavigationControl_Open_in_new_tab", resourceCulture);
            }
        }
        
        public static string NavigationControl_NavigationControl_Open_in_new_panel {
            get {
                return ResourceManager.GetString("NavigationControl_NavigationControl_Open_in_new_panel", resourceCulture);
            }
        }
        
        public static string TopBar_Help_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_Help_ToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginPage_AddMod_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_AddMod_ToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginPage_DeleteMod_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_DeleteMod_ToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginPage_AddModAdvanced_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_AddModAdvanced_ToolTip", resourceCulture);
            }
        }
        
        public static string ApplyControlView_ViewApplyChanges_ToolTip {
            get {
                return ResourceManager.GetString("ApplyControlView_ViewApplyChanges_ToolTip", resourceCulture);
            }
        }
        
        public static string ApplyControlView_Apply_ToolTip {
            get {
                return ResourceManager.GetString("ApplyControlView_Apply_ToolTip", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_Added {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_Added", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFile {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFile", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_Removed {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_Removed", resourceCulture);
            }
        }
        
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFolder {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFolder", resourceCulture);
            }
        }
        
        public static string InfoBanner_PrefixProperty_Did_you_know_ {
            get {
                return ResourceManager.GetString("InfoBanner_PrefixProperty_Did_you_know_", resourceCulture);
            }
        }
        
        public static string NewTabPageInfoBannerText1 {
            get {
                return ResourceManager.GetString("NewTabPageInfoBannerText1", resourceCulture);
            }
        }
        
        public static string NewTabPageInfoBannerText2 {
            get {
                return ResourceManager.GetString("NewTabPageInfoBannerText2", resourceCulture);
            }
        }
        
        public static string LoadoutGrid_EmptyModlistSubtitle_Add_from_library {
            get {
                return ResourceManager.GetString("LoadoutGrid_EmptyModlistSubtitle_Add_from_library", resourceCulture);
            }
        }
        
        public static string LoadoutGridViewModel_EmptyModlistTitleString {
            get {
                return ResourceManager.GetString("LoadoutGridViewModel_EmptyModlistTitleString", resourceCulture);
            }
        }
        
        public static string EmptyLibraryTitleText {
            get {
                return ResourceManager.GetString("EmptyLibraryTitleText", resourceCulture);
            }
        }
        
        public static string FileOriginsPageViewModel_EmptyLibrarySubtitleText {
            get {
                return ResourceManager.GetString("FileOriginsPageViewModel_EmptyLibrarySubtitleText", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_Page_Title {
            get {
                return ResourceManager.GetString("DiagnosticListView.Page_Title", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_Page_Description {
            get {
                return ResourceManager.GetString("DiagnosticListView.Page_Description", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_EmptyState_Header {
            get {
                return ResourceManager.GetString("DiagnosticListView.EmptyState.Header", resourceCulture);
            }
        }
        
        public static string DiagnosticListView_EmptyState_Subtitle {
            get {
                return ResourceManager.GetString("DiagnosticListView.EmptyState.Subtitle", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewModel_CreationTimeConverter_Created__0_ {
            get {
                return ResourceManager.GetString("LoadoutCardViewModel_CreationTimeConverter_Created__0_", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewModel_FormatLastAppliedTime_Last_applied__0_ {
            get {
                return ResourceManager.GetString("LoadoutCardViewModel_FormatLastAppliedTime_Last_applied__0_", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewModel_FormatNumMods_Mods__0_ {
            get {
                return ResourceManager.GetString("LoadoutCardViewModel_FormatNumMods_Mods__0_", resourceCulture);
            }
        }
        
        public static string MyLoadoutsPageTitle {
            get {
                return ResourceManager.GetString("MyLoadoutsPageTitle", resourceCulture);
            }
        }
        
        public static string MyLoadoutsPageDescriptionText {
            get {
                return ResourceManager.GetString("MyLoadoutsPageDescriptionText", resourceCulture);
            }
        }
        
        public static string SettingsView_Description {
            get {
                return ResourceManager.GetString("SettingsView_Description", resourceCulture);
            }
        }
        
        public static string MyLoadoutsGameSectionHeading {
            get {
                return ResourceManager.GetString("MyLoadoutsGameSectionHeading", resourceCulture);
            }
        }
        
        public static string CreateNewLoadoutCarViewTexBlock {
            get {
                return ResourceManager.GetString("CreateNewLoadoutCarViewTexBlock", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewCurrentlyAppliedTextBlock {
            get {
                return ResourceManager.GetString("LoadoutCardViewCurrentlyAppliedTextBlock", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewCreateCopyButton {
            get {
                return ResourceManager.GetString("LoadoutCardViewCreateCopyButton", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewDeletingText {
            get {
                return ResourceManager.GetString("LoadoutCardViewDeletingText", resourceCulture);
            }
        }
        
        public static string LoadoutCardViewCreatingText {
            get {
                return ResourceManager.GetString("LoadoutCardViewCreatingText", resourceCulture);
            }
        }
        
        public static string MyLoadoutsEmptyState_Subtitle {
            get {
                return ResourceManager.GetString("MyLoadoutsEmptyState_Subtitle", resourceCulture);
            }
        }
        
        public static string MyLoadoutsEmptyState_Header {
            get {
                return ResourceManager.GetString("MyLoadoutsEmptyState_Header", resourceCulture);
            }
        }
        
        public static string LibraryItemDeleteConfirmation_Title {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_Title", resourceCulture);
            }
        }
        
        public static string LibraryItemDeleteConfirmation_HeaderQuestion {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_HeaderQuestion", resourceCulture);
            }
        }
        
        public static string LibraryItemDeleteConfirmation_UsedBy {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_UsedBy", resourceCulture);
            }
        }
        
        public static string LibraryItemDeleteConfirmation_UsedByWithLoadout {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_UsedByWithLoadout", resourceCulture);
            }
        }
        
        public static string LibraryItemDeleteConfirmation_DeleteModsButton {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_DeleteModsButton", resourceCulture);
            }
        }
        
        public static string Updated_ViewUninstallDocs {
            get {
                return ResourceManager.GetString("Updated_ViewUninstallDocs", resourceCulture);
            }
        }
        
        public static string HumanizedDateTime_Never {
            get {
                return ResourceManager.GetString("HumanizedDateTime_Never", resourceCulture);
            }
        }
        
        public static string ApplyControlView__ApplyingToolTip {
            get {
                return ResourceManager.GetString("ApplyControlView__ApplyingToolTip", resourceCulture);
            }
        }
        
        public static string LoadoutCard_DeleteLoadoutToolTip {
            get {
                return ResourceManager.GetString("LoadoutCard_DeleteLoadoutToolTip", resourceCulture);
            }
        }
        
        public static string LoadoutView_Title_Installed_Mods {
            get {
                return ResourceManager.GetString("LoadoutView_Title_Installed_Mods", resourceCulture);
            }
        }
        
        public static string LoadoutView_Title_Installed_Mods_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutView_Title_Installed_Mods_ToolTip", resourceCulture);
            }
        }
        
        public static string ErrorGameAlreadyRunning_Title {
            get {
                return ResourceManager.GetString("ErrorGameAlreadyRunning_Title", resourceCulture);
            }
        }
        
        public static string ErrorGameAlreadyRunning_Description {
            get {
                return ResourceManager.GetString("ErrorGameAlreadyRunning_Description", resourceCulture);
            }
        }
        
        public static string FileOriginPage_SwitchView {
            get {
                return ResourceManager.GetString("FileOriginPage_SwitchView", resourceCulture);
            }
        }
        
        public static string FileOriginPage_SwitchView_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_SwitchView_ToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_FromDrive_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromDrive_ToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_FromNexus_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromNexus_ToolTip", resourceCulture);
            }
        }
        
        public static string FileOriginsPage_CheckForUpdates_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginsPage_CheckForUpdates_ToolTip", resourceCulture);
            }
        }
        
        public static string TopBar_Forward_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_Forward_ToolTip", resourceCulture);
            }
        }
        
        public static string TopBar_Back_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_Back_ToolTip", resourceCulture);
            }
        }
        
        public static string TopBar_GiveFeedback_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_GiveFeedback_ToolTip", resourceCulture);
            }
        }
        
        public static string TopBarActions__LOG_IN_ToolTip {
            get {
                return ResourceManager.GetString("TopBarActions__LOG_IN_ToolTip", resourceCulture);
            }
        }
        
        public static string LoadoutGridView__Remove_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutGridView__Remove_ToolTip", resourceCulture);
            }
        }
        
        public static string LoadoutGridView__View_Files_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutGridView__View_Files_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_Ready_to_install {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_Ready_to_install", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_Num_required_mods_downloaded {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_Num_required_mods_downloaded", resourceCulture);
            }
        }
        
        public static string FileOriginPage_UpdateAll {
            get {
                return ResourceManager.GetString("FileOriginPage_UpdateAll", resourceCulture);
            }
        }
        
        public static string LeftMenu_Label_Installed_Mods {
            get {
                return ResourceManager.GetString("LeftMenu_Label_Installed_Mods", resourceCulture);
            }
        }
        
        public static string LeftMenu_Label_Utilities {
            get {
                return ResourceManager.GetString("LeftMenu_Label_Utilities", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_CollectionDownloadViewModel_Ready_to_play___All_required_mods_installed {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_CollectionDownloadViewModel_Ready_to_play___All_requi" +
                        "red_mods_installed", resourceCulture);
            }
        }
        
        public static string LibraryItemButtonUpdate_Single {
            get {
                return ResourceManager.GetString("LibraryItemButtonUpdate_Single", resourceCulture);
            }
        }
        
        public static string LibraryItemButtonUpdate_CounterInBracket {
            get {
                return ResourceManager.GetString("LibraryItemButtonUpdate_CounterInBracket", resourceCulture);
            }
        }
        
        public static string LibraryItemButtonUpdate_All {
            get {
                return ResourceManager.GetString("LibraryItemButtonUpdate_All", resourceCulture);
            }
        }
        
        public static string LoadoutView_Title_Installed_Mods_Default {
            get {
                return ResourceManager.GetString("LoadoutView_Title_Installed_Mods_Default", resourceCulture);
            }
        }
        
        public static string LoadoutLeftMenuViewModel_External_Changes {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_External_Changes", resourceCulture);
            }
        }
        
        public static string LoadoutLeftMenuViewModel_External_Changes_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_External_Changes_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_DownloadRequired {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_DownloadRequired", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_InstallCollection {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_InstallCollection", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_ViewCollection {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_ViewCollection", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_UpdateCollection {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_UpdateCollection", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_DownloadOptional {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_DownloadOptional", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_InstallOptional {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_InstallOptional", resourceCulture);
            }
        }
        
        public static string RemoveGameOverlayView_Title {
            get {
                return ResourceManager.GetString("RemoveGameOverlayView_Title", resourceCulture);
            }
        }
        
        public static string RemoveGameOverlayView_Description {
            get {
                return ResourceManager.GetString("RemoveGameOverlayView_Description", resourceCulture);
            }
        }
        
        public static string RemoveGameOverlayView_ToggleDescription {
            get {
                return ResourceManager.GetString("RemoveGameOverlayView_ToggleDescription", resourceCulture);
            }
        }
        
        public static string RemoveGameOverlayView_CancelButton {
            get {
                return ResourceManager.GetString("RemoveGameOverlayView_CancelButton", resourceCulture);
            }
        }
        
        public static string RemoveGameOverlayView_RemoveButton {
            get {
                return ResourceManager.GetString("RemoveGameOverlayView_RemoveButton", resourceCulture);
            }
        }
        
        public static string RemoveGameOverlayView_RemoveButton_AlsoDelete {
            get {
                return ResourceManager.GetString("RemoveGameOverlayView_RemoveButton_AlsoDelete", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_InfoTitle {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_InfoTitle", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_InfoDescription {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_InfoDescription", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_InfoStep1 {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_InfoStep1", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_InfoStep2 {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_InfoStep2", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_InfoStep3 {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_InfoStep3", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_InfoInstructionsDescription {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_InfoInstructionsDescription", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_CheckingTitle {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_CheckingTitle", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_CheckingText {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_CheckingText", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_ErrorTitle {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_ErrorTitle", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_ErrorStep1 {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_ErrorStep1", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_ErrorStep2 {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_ErrorStep2", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_ErrorStep3 {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_ErrorStep3", resourceCulture);
            }
        }
        
        public static string ManualDownloadRequiredOverlayView_ErrorReportBugText {
            get {
                return ResourceManager.GetString("ManualDownloadRequiredOverlayView_ErrorReportBugText", resourceCulture);
            }
        }
        
        public static string CollectionComponents_ExternalDownloadAction_ToolTip {
            get {
                return ResourceManager.GetString("CollectionComponents_ExternalDownloadAction_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionComponents_ManualDownloadAction_ToolTip {
            get {
                return ResourceManager.GetString("CollectionComponents_ManualDownloadAction_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_StatsMods_ToolTip {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_StatsMods_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_StatsEndorsements_ToolTip {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_StatsEndorsements_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_StatsDownloads_ToolTip {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_StatsDownloads_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_StatsSize_ToolTip {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_StatsSize_ToolTip", resourceCulture);
            }
        }
        
        public static string CollectionDownloadViewModel_StatsRating_ToolTip {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_StatsRating_ToolTip", resourceCulture);
            }
        }
        
        public static string ManageGameWarning_Title {
            get {
                return ResourceManager.GetString("ManageGameWarning_Title", resourceCulture);
            }
        }
        
        public static string ManageGameWarning_Desc1 {
            get {
                return ResourceManager.GetString("ManageGameWarning_Desc1", resourceCulture);
            }
        }
        
        public static string ManageGameWarning_Desc2 {
            get {
                return ResourceManager.GetString("ManageGameWarning_Desc2", resourceCulture);
            }
        }
        
        public static string ManageGameWarning_Cancel {
            get {
                return ResourceManager.GetString("ManageGameWarning_Cancel", resourceCulture);
            }
        }
        
        public static string ManageGameWarning_Continue {
            get {
                return ResourceManager.GetString("ManageGameWarning_Continue", resourceCulture);
            }
        }
    }
}
