//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusMods.App.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NexusMods.App.UI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a panel for split screen viewing.
        /// </summary>
        public static string AddPanelToolTip {
            get {
                return ResourceManager.GetString("AddPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying changes to the game.
        /// </summary>
        public static string ApplyControlView__ApplyingToolTip {
            get {
                return ResourceManager.GetString("ApplyControlView__ApplyingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply your changes to the game folder.
        /// </summary>
        public static string ApplyControlView_Apply_ToolTip {
            get {
                return ResourceManager.GetString("ApplyControlView_Apply_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview changes.
        /// </summary>
        public static string ApplyControlView_ViewApplyChanges {
            get {
                return ResourceManager.GetString("ApplyControlView_ViewApplyChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the changes that will be applied to your game folder.
        /// </summary>
        public static string ApplyControlView_ViewApplyChanges_ToolTip {
            get {
                return ResourceManager.GetString("ApplyControlView_ViewApplyChanges_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate &amp; Apply.
        /// </summary>
        public static string ApplyControlViewModel__ACTIVATE_AND_APPLY {
            get {
                return ResourceManager.GetString("ApplyControlViewModel__ACTIVATE_AND_APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Loadout.
        /// </summary>
        public static string ApplyControlViewModel__ACTIVATE_LOADOUT {
            get {
                return ResourceManager.GetString("ApplyControlViewModel__ACTIVATE_LOADOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string ApplyControlViewModel__APPLY {
            get {
                return ResourceManager.GetString("ApplyControlViewModel__APPLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string ApplyDiff_Refresh {
            get {
                return ResourceManager.GetString("ApplyDiff_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview changes.
        /// </summary>
        public static string ApplyDiffViewModel_PageTitle {
            get {
                return ResourceManager.GetString("ApplyDiffViewModel_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying....
        /// </summary>
        public static string ApplyingControlView__ApplyingText {
            get {
                return ResourceManager.GetString("ApplyingControlView__ApplyingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 mins.
        /// </summary>
        public static string BoldMinutesRemainingTextBlock {
            get {
                return ResourceManager.GetString("BoldMinutesRemainingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Games.
        /// </summary>
        public static string BrowseGames {
            get {
                return ResourceManager.GetString("BrowseGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Button_Manage {
            get {
                return ResourceManager.GetString("Button_Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        public static string CancelDownloadOverlayView_Description__Download {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Description__Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will be cancelled and the files will be deleted..
        /// </summary>
        public static string CancelDownloadOverlayView_Description_download_will_be_cancelled {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Description_download_will_be_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string CancelDownloadOverlayView_Description_downloads {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Description_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel and delete downloads?.
        /// </summary>
        public static string CancelDownloadOverlayView_Title {
            get {
                return ResourceManager.GetString("CancelDownloadOverlayView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string ChangelogPageViewModel_ChangelogPageViewModel_Changelog {
            get {
                return ResourceManager.GetString("ChangelogPageViewModel_ChangelogPageViewModel_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to play - All required mods installed.
        /// </summary>
        public static string CollectionDownloadViewModel_CollectionDownloadViewModel_Ready_to_play___All_required_mods_installed {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_CollectionDownloadViewModel_Ready_to_play___All_requi" +
                        "red_mods_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all optional mods.
        /// </summary>
        public static string CollectionDownloadViewModel_DownloadOptional {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_DownloadOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all required mods.
        /// </summary>
        public static string CollectionDownloadViewModel_DownloadRequired {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_DownloadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Collection.
        /// </summary>
        public static string CollectionDownloadViewModel_InstallCollection {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_InstallCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install downloaded optional mods.
        /// </summary>
        public static string CollectionDownloadViewModel_InstallOptional {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_InstallOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} required mods downloaded.
        /// </summary>
        public static string CollectionDownloadViewModel_Num_required_mods_downloaded {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_Num_required_mods_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to install - All required mods downloaded.
        /// </summary>
        public static string CollectionDownloadViewModel_Ready_to_install {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_Ready_to_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Update.
        /// </summary>
        public static string CollectionDownloadViewModel_UpdateCollection {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_UpdateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Installed Collection.
        /// </summary>
        public static string CollectionDownloadViewModel_ViewCollection {
            get {
                return ResourceManager.GetString("CollectionDownloadViewModel_ViewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new.
        /// </summary>
        public static string CreateNewLoadoutCarViewTexBlock {
            get {
                return ResourceManager.GetString("CreateNewLoadoutCarViewTexBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Error.
        /// </summary>
        public static string DiagnosticDetailsView_SeverityTitle_CRITICAL_ERROR {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_CRITICAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        public static string DiagnosticDetailsView_SeverityTitle_HIDDEN {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_HIDDEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string DiagnosticDetailsView_SeverityTitle_SUGGESTION {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_SUGGESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string DiagnosticDetailsView_SeverityTitle_WARNING {
            get {
                return ResourceManager.GetString("DiagnosticDetailsView_SeverityTitle_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ({0}).
        /// </summary>
        public static string DiagnosticListView_DiagnosticListView_All {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical ({0}).
        /// </summary>
        public static string DiagnosticListView_DiagnosticListView_Critical {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions ({0}).
        /// </summary>
        public static string DiagnosticListView_DiagnosticListView_Suggestions {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no diagnostics.
        /// </summary>
        public static string DiagnosticListView_DiagnosticListView_There_are_no_diagnostics {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_There_are_no_diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings ({0}).
        /// </summary>
        public static string DiagnosticListView_DiagnosticListView_Warnings {
            get {
                return ResourceManager.GetString("DiagnosticListView_DiagnosticListView_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loadout passed the health check without issues.
        /// </summary>
        public static string DiagnosticListView_EmptyState_Header {
            get {
                return ResourceManager.GetString("DiagnosticListView.EmptyState.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for gaming..
        /// </summary>
        public static string DiagnosticListView_EmptyState_Subtitle {
            get {
                return ResourceManager.GetString("DiagnosticListView.EmptyState.Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your Loadout for any issues and learn how to resolve them if needed.
        /// </summary>
        public static string DiagnosticListView_Page_Description {
            get {
                return ResourceManager.GetString("DiagnosticListView.Page_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string DiagnosticListView_Page_Title {
            get {
                return ResourceManager.GetString("DiagnosticListView.Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string DiagnosticListViewModel_DiagnosticListViewModel_Diagnostics {
            get {
                return ResourceManager.GetString("DiagnosticListViewModel_DiagnosticListViewModel_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogButton_CANCEL {
            get {
                return ResourceManager.GetString("DialogButton_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete mod(s).
        /// </summary>
        public static string DialogButton_DELETE_MODS {
            get {
                return ResourceManager.GetString("DialogButton_DELETE_MODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string DialogButton_Discard {
            get {
                return ResourceManager.GetString("DialogButton_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string DialogButton_SAVE {
            get {
                return ResourceManager.GetString("DialogButton_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply changes: Adding {0} Modifying {1} Removing {2}.
        /// </summary>
        public static string DiffTreeViewModel_StatusBar__Apply_changes {
            get {
                return ResourceManager.GetString("DiffTreeViewModel_StatusBar__Apply_changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to process: {0}.
        /// </summary>
        public static string DiffTreeViewModel_StatusBar__Data_to_process___0_ {
            get {
                return ResourceManager.GetString("DiffTreeViewModel_StatusBar__Data_to_process___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: Loadout {0} ({1})  Disk {2} ({3}).
        /// </summary>
        public static string DiffTreeViewModel_StatusBar__File_Loadout_Disk {
            get {
                return ResourceManager.GetString("DiffTreeViewModel_StatusBar__File_Loadout_Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string DownloadCompleted_Clear_All {
            get {
                return ResourceManager.GetString("DownloadCompleted_Clear_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string DownloadCompleted_COMPLETED {
            get {
                return ResourceManager.GetString("DownloadCompleted_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string DownloadHistoryView__HISTORY {
            get {
                return ResourceManager.GetString("DownloadHistoryView__HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DownloadInProgressView__Cancel {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DownloadInProgressView__Clear {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear completed.
        /// </summary>
        public static string DownloadInProgressView__Clear_completed {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Clear_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string DownloadInProgressView__IN_PROGRESS {
            get {
                return ResourceManager.GetString("DownloadInProgressView__IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string DownloadInProgressView__Pause {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause all.
        /// </summary>
        public static string DownloadInProgressView__Pause_All {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Pause_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string DownloadInProgressView__Resume {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume All.
        /// </summary>
        public static string DownloadInProgressView__Resume_All {
            get {
                return ResourceManager.GetString("DownloadInProgressView__Resume_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in library.
        /// </summary>
        public static string DownloadInProgressView__View_in_library {
            get {
                return ResourceManager.GetString("DownloadInProgressView__View_in_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads_WorkspaceTitle {
            get {
                return ResourceManager.GetString("Downloads_WorkspaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string DownloadStatus_Idle {
            get {
                return ResourceManager.GetString("DownloadStatus_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string DownloadStatus_Progress {
            get {
                return ResourceManager.GetString("DownloadStatus_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyzing.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Analyzing {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Analyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Cancelled {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Complete {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Downloading {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Installing {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Paused {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string DownloadStatusDesignViewModel_FormatStatus_Queued {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_FormatStatus_Queued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued 0%.
        /// </summary>
        public static string DownloadStatusDesignViewModel_Text_Queued_0_ {
            get {
                return ResourceManager.GetString("DownloadStatusDesignViewModel_Text_Queued_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string DownloadsView__Completed {
            get {
                return ResourceManager.GetString("DownloadsView__Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download history.
        /// </summary>
        public static string DownloadsView__Download_history {
            get {
                return ResourceManager.GetString("DownloadsView__Download_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string DownloadsView__DOWNLOADS {
            get {
                return ResourceManager.GetString("DownloadsView__DOWNLOADS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string DownloadsView__In_Progress {
            get {
                return ResourceManager.GetString("DownloadsView__In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Downloads page is currently being reworked and will be replaced in a future update. We apologise for the inconvenience..
        /// </summary>
        public static string DownloadsView_UnderDevelopment {
            get {
                return ResourceManager.GetString("DownloadsView_UnderDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DownloadTaskViewModel_Field_Unknown {
            get {
                return ResourceManager.GetString("DownloadTaskViewModel_Field_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string DownloadTaskViewModel_Version_Unknown {
            get {
                return ResourceManager.GetString("DownloadTaskViewModel_Version_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods in your Library.
        /// </summary>
        public static string EmptyLibraryTitleText {
            get {
                return ResourceManager.GetString("EmptyLibraryTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like {0} is already running.
        ///To apply changes or launch the game again, please close the game first..
        /// </summary>
        public static string ErrorGameAlreadyRunning_Description {
            get {
                return ResourceManager.GetString("ErrorGameAlreadyRunning_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game is currently running.
        /// </summary>
        public static string ErrorGameAlreadyRunning_Title {
            get {
                return ResourceManager.GetString("ErrorGameAlreadyRunning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mod you&apos;re trying to access has been deleted or is missing..
        /// </summary>
        public static string ErrorView_MissingMod_Description {
            get {
                return ResourceManager.GetString("ErrorView_MissingMod_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod not found.
        /// </summary>
        public static string ErrorView_MissingMod_Subheader {
            get {
                return ResourceManager.GetString("ErrorView_MissingMod_Subheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string ErrorView_Title {
            get {
                return ResourceManager.GetString("ErrorView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string FileOriginPage_AddMod {
            get {
                return ResourceManager.GetString("FileOriginPage_AddMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the selected mod(s) to this loadout.
        /// </summary>
        public static string FileOriginPage_AddMod_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_AddMod_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced add.
        /// </summary>
        public static string FileOriginPage_AddModAdvanced {
            get {
                return ResourceManager.GetString("FileOriginPage_AddModAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select specific files from a mod to add to your loadout.
        /// </summary>
        public static string FileOriginPage_AddModAdvanced_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_AddModAdvanced_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string FileOriginPage_DeleteMod {
            get {
                return ResourceManager.GetString("FileOriginPage_DeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently remove this mod from your Library.
        /// </summary>
        public static string FileOriginPage_DeleteMod_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_DeleteMod_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch View.
        /// </summary>
        public static string FileOriginPage_SwitchView {
            get {
                return ResourceManager.GetString("FileOriginPage_SwitchView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide mod page groups.
        /// </summary>
        public static string FileOriginPage_SwitchView_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginPage_SwitchView_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string FileOriginPage_UpdateAll {
            get {
                return ResourceManager.GetString("FileOriginPage_UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string FileOriginsPage_AddButtonText {
            get {
                return ResourceManager.GetString("FileOriginsPage_AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From drive.
        /// </summary>
        public static string FileOriginsPage_FromDrive {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import a mod from your computer.
        /// </summary>
        public static string FileOriginsPage_FromDrive_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromDrive_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Nexus Mods.
        /// </summary>
        public static string FileOriginsPage_FromNexus_ToolTip {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromNexus_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Nexus Mods.
        /// </summary>
        public static string FileOriginsPage_FromNexusMods {
            get {
                return ResourceManager.GetString("FileOriginsPage_FromNexusMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get mods:.
        /// </summary>
        public static string FileOriginsPage_GetMods {
            get {
                return ResourceManager.GetString("FileOriginsPage_GetMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string FileOriginsPage_ViewButtonText {
            get {
                return ResourceManager.GetString("FileOriginsPage_ViewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIONS.
        /// </summary>
        public static string FileOriginsPageView_ActionHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_ActionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOADED.
        /// </summary>
        public static string FileOriginsPageView_DownloadedHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_DownloadedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLED.
        /// </summary>
        public static string FileOriginsPageView_InstalledHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_InstalledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD NAME.
        /// </summary>
        public static string FileOriginsPageView_NameHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE.
        /// </summary>
        public static string FileOriginsPageView_SizeHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_SizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION.
        /// </summary>
        public static string FileOriginsPageView_VersionHeader {
            get {
                return ResourceManager.GetString("FileOriginsPageView_VersionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download {0} mods from Nexus Mods.
        /// </summary>
        public static string FileOriginsPageViewModel_EmptyLibrarySubtitleText {
            get {
                return ResourceManager.GetString("FileOriginsPageViewModel_EmptyLibrarySubtitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string FileTreeNodeView__View {
            get {
                return ResourceManager.GetString("FileTreeNodeView__View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game.
        /// </summary>
        public static string GameWidget__Add_game {
            get {
                return ResourceManager.GetString("GameWidget__Add_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding game.
        /// </summary>
        public static string GameWidget__Adding_game {
            get {
                return ResourceManager.GetString("GameWidget__Adding_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the game and all mods installed by the app.
        /// </summary>
        public static string GameWidget__RemoveGame_ToolTip {
            get {
                return ResourceManager.GetString("GameWidget__RemoveGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing game.
        /// </summary>
        public static string GameWidget__Removing_game {
            get {
                return ResourceManager.GetString("GameWidget__Removing_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string GameWidget__View {
            get {
                return ResourceManager.GetString("GameWidget__View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Helpers_ERROR {
            get {
                return ResourceManager.GetString("Helpers_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        public static string Helpers_GenerateHeader_CATEGORY {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FILE COUNT.
        /// </summary>
        public static string Helpers_GenerateHeader_File_Count {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_File_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME.
        /// </summary>
        public static string Helpers_GenerateHeader_GAME {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLED.
        /// </summary>
        public static string Helpers_GenerateHeader_INSTALLED {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_INSTALLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOD NAME.
        /// </summary>
        public static string Helpers_GenerateHeader_MOD_NAME {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_MOD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        public static string Helpers_GenerateHeader_NAME {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE.
        /// </summary>
        public static string Helpers_GenerateHeader_SIZE {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATE.
        /// </summary>
        public static string Helpers_GenerateHeader_State {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATUS.
        /// </summary>
        public static string Helpers_GenerateHeader_STATUS {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERSION.
        /// </summary>
        public static string Helpers_GenerateHeader_VERSION {
            get {
                return ResourceManager.GetString("Helpers_GenerateHeader_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse all games.
        /// </summary>
        public static string HomeView__BROWSE_ALL_GAMES {
            get {
                return ResourceManager.GetString("HomeView__BROWSE_ALL_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t see your game.
        /// </summary>
        public static string HomeView__CANT_SEE_YOUR_GAME {
            get {
                return ResourceManager.GetString("HomeView__CANT_SEE_YOUR_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found games ready to mod!.
        /// </summary>
        public static string HomeView__We_found_games {
            get {
                return ResourceManager.GetString("HomeView__We_found_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeWorkspace_Title {
            get {
                return ResourceManager.GetString("HomeWorkspace_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string HumanizedDateTime_Never {
            get {
                return ResourceManager.GetString("HumanizedDateTime_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be added.
        /// </summary>
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_Added {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be modified.
        /// </summary>
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFile {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder contains modified files.
        /// </summary>
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFolder {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_ModifiedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will be removed.
        /// </summary>
        public static string IFileTreeNodeViewModel_FormattedChangeStateToolTip_Removed {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_FormattedChangeStateToolTip_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Added {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents modified.
        /// </summary>
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Contents_modified {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Contents_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Modified {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed.
        /// </summary>
        public static string IFileTreeNodeViewModel_ToFormattedChangeState_Removed {
            get {
                return ResourceManager.GetString("IFileTreeNodeViewModel_ToFormattedChangeState_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know?.
        /// </summary>
        public static string InfoBanner_PrefixProperty_Did_you_know_ {
            get {
                return ResourceManager.GetString("InfoBanner_PrefixProperty_Did_you_know_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingest.
        /// </summary>
        public static string IngestButtonTextBlock_Text {
            get {
                return ResourceManager.GetString("IngestButtonTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Downloads.
        /// </summary>
        public static string InProgress_NoDownloadsTextBlock {
            get {
                return ResourceManager.GetString("InProgress_NoDownloadsTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string InProgressDownloadsPage_Title {
            get {
                return ResourceManager.GetString("InProgressDownloadsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string InProgressTitleTextBlock {
            get {
                return ResourceManager.GetString("InProgressTitleTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string InProgressView_InProgressView_Remaining {
            get {
                return ResourceManager.GetString("InProgressView_InProgressView_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string LaunchButtonViewModel_LaunchGame_LAUNCH {
            get {
                return ResourceManager.GetString("LaunchButtonViewModel_LaunchGame_LAUNCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME RUNNING....
        /// </summary>
        public static string LaunchButtonViewModel_LaunchGame_RUNNING {
            get {
                return ResourceManager.GetString("LaunchButtonViewModel_LaunchGame_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to launch the game.
        /// </summary>
        public static string LaunchButtonViewModel_LaunchGame_ToolTip {
            get {
                return ResourceManager.GetString("LaunchButtonViewModel_LaunchGame_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLED MODS.
        /// </summary>
        public static string LeftMenu_Label_Installed_Mods {
            get {
                return ResourceManager.GetString("LeftMenu_Label_Installed_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTILITIES.
        /// </summary>
        public static string LeftMenu_Label_Utilities {
            get {
                return ResourceManager.GetString("LeftMenu_Label_Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all.
        /// </summary>
        public static string LibraryItemButtonUpdate_All {
            get {
                return ResourceManager.GetString("LibraryItemButtonUpdate_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update ({0}).
        /// </summary>
        public static string LibraryItemButtonUpdate_CounterInBracket {
            get {
                return ResourceManager.GetString("LibraryItemButtonUpdate_CounterInBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download update.
        /// </summary>
        public static string LibraryItemButtonUpdate_Single {
            get {
                return ResourceManager.GetString("LibraryItemButtonUpdate_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete mod(s).
        /// </summary>
        public static string LibraryItemDeleteConfirmation_DeleteModsButton {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_DeleteModsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting these mods permanently removes them from the app:.
        /// </summary>
        public static string LibraryItemDeleteConfirmation_HeaderQuestion {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_HeaderQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete mod(s).
        /// </summary>
        public static string LibraryItemDeleteConfirmation_Title {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by {0}:.
        /// </summary>
        public static string LibraryItemDeleteConfirmation_UsedBy {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_UsedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used by {0} - {1}:.
        /// </summary>
        public static string LibraryItemDeleteConfirmation_UsedByWithLoadout {
            get {
                return ResourceManager.GetString("LibraryItemDeleteConfirmation_UsedByWithLoadout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string LibraryPageTitle {
            get {
                return ResourceManager.GetString("LibraryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage downloaded mods and collections.
        /// </summary>
        public static string LibraryPageTitleToolTip {
            get {
                return ResourceManager.GetString("LibraryPageTitleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Loadout.
        /// </summary>
        public static string LoadoutCard_DeleteLoadoutToolTip {
            get {
                return ResourceManager.GetString("LoadoutCard_DeleteLoadoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        public static string LoadoutCardViewCreateCopyButton {
            get {
                return ResourceManager.GetString("LoadoutCardViewCreateCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        public static string LoadoutCardViewCreatingText {
            get {
                return ResourceManager.GetString("LoadoutCardViewCreatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Applied.
        /// </summary>
        public static string LoadoutCardViewCurrentlyAppliedTextBlock {
            get {
                return ResourceManager.GetString("LoadoutCardViewCurrentlyAppliedTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting....
        /// </summary>
        public static string LoadoutCardViewDeletingText {
            get {
                return ResourceManager.GetString("LoadoutCardViewDeletingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created {0}.
        /// </summary>
        public static string LoadoutCardViewModel_CreationTimeConverter_Created__0_ {
            get {
                return ResourceManager.GetString("LoadoutCardViewModel_CreationTimeConverter_Created__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last applied: {0}.
        /// </summary>
        public static string LoadoutCardViewModel_FormatLastAppliedTime_Last_applied__0_ {
            get {
                return ResourceManager.GetString("LoadoutCardViewModel_FormatLastAppliedTime_Last_applied__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods {0}.
        /// </summary>
        public static string LoadoutCardViewModel_FormatNumMods_Mods__0_ {
            get {
                return ResourceManager.GetString("LoadoutCardViewModel_FormatNumMods_Mods__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install your mods from the Library.
        /// </summary>
        public static string LoadoutGrid_EmptyModlistSubtitle_Add_from_library {
            get {
                return ResourceManager.GetString("LoadoutGrid_EmptyModlistSubtitle_Add_from_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string LoadoutGridView__Remove {
            get {
                return ResourceManager.GetString("LoadoutGridView__Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the selected mod(s) from this loadout.
        /// </summary>
        public static string LoadoutGridView__Remove_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutGridView__Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mod files.
        /// </summary>
        public static string LoadoutGridView__View_Files {
            get {
                return ResourceManager.GetString("LoadoutGridView__View_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LoadoutGridView__View_Files_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutGridView__View_Files_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a mod file to install..
        /// </summary>
        public static string LoadoutGridView_AddMod_FilePicker_Title {
            get {
                return ResourceManager.GetString("LoadoutGridView_AddMod_FilePicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string LoadoutGridView_AddMod_FileType_Archive {
            get {
                return ResourceManager.GetString("LoadoutGridView_AddMod_FileType_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mods added to {0}.
        /// </summary>
        public static string LoadoutGridViewModel_EmptyModlistTitleString {
            get {
                return ResourceManager.GetString("LoadoutGridViewModel_EmptyModlistTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your Loadout for any issues and learn how to resolve them if needed.
        /// </summary>
        public static string LoadoutLeftMenuViewModel_Diagnostics_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_Diagnostics_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Changes.
        /// </summary>
        public static string LoadoutLeftMenuViewModel_External_Changes {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_External_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review, remove, or restore changes made outside the app..
        /// </summary>
        public static string LoadoutLeftMenuViewModel_External_Changes_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_External_Changes_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Check.
        /// </summary>
        public static string LoadoutLeftMenuViewModel_LoadoutLeftMenuViewModel_Diagnostics {
            get {
                return ResourceManager.GetString("LoadoutLeftMenuViewModel_LoadoutLeftMenuViewModel_Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All ({0}).
        /// </summary>
        public static string LoadoutView_Title_Installed_Mods {
            get {
                return ResourceManager.GetString("LoadoutView_Title_Installed_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string LoadoutView_Title_Installed_Mods_Default {
            get {
                return ResourceManager.GetString("LoadoutView_Title_Installed_Mods_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and manage all installed mods.
        /// </summary>
        public static string LoadoutView_Title_Installed_Mods_ToolTip {
            get {
                return ResourceManager.GetString("LoadoutView_Title_Installed_Mods_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string LoadoutViewPageTitle {
            get {
                return ResourceManager.GetString("LoadoutViewPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To easily download mods from Nexus Mods you will need to log in with your Nexus Mods account. /// ///To add mods manually from your drive, you do not need to log in..
        /// </summary>
        public static string LoginMessageView_BodyTextBlock {
            get {
                return ResourceManager.GetString("LoginMessageView_BodyTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to get started.
        /// </summary>
        public static string LoginMessageView_Title {
            get {
                return ResourceManager.GetString("LoginMessageView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max panels reached.
        /// </summary>
        public static string MaxPanelsAddedToolTip {
            get {
                return ResourceManager.GetString("MaxPanelsAddedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string MessageBox_Button_No {
            get {
                return ResourceManager.GetString("MessageBox_Button_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MessageBox_Button_Ok {
            get {
                return ResourceManager.GetString("MessageBox_Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string MessageBox_Button_Yes {
            get {
                return ResourceManager.GetString("MessageBox_Button_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string MetricsOptIn_ALLOW {
            get {
                return ResourceManager.GetString("MetricsOptIn_ALLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string MetricsOptIn_DENY {
            get {
                return ResourceManager.GetString("MetricsOptIn_DENY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us provide you with the best modding experience.
        ///
        ///With your permission, we will collect analytics information and send it to our team to help us improve quality and performance.
        ///
        ///This information is sent anonymously and will never be shared with a 3rd party..
        /// </summary>
        public static string MetricsOptIn_MainMessage {
            get {
                return ResourceManager.GetString("MetricsOptIn_MainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info about the data we track.
        /// </summary>
        public static string MetricsOptIn_MoreInfoAboutTheDataWeTrack {
            get {
                return ResourceManager.GetString("MetricsOptIn_MoreInfoAboutTheDataWeTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics and usage data.
        /// </summary>
        public static string MetricsOptIn_OverlayTitle {
            get {
                return ResourceManager.GetString("MetricsOptIn_OverlayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining.
        /// </summary>
        public static string MinutesRemainingTextBlock {
            get {
                return ResourceManager.GetString("MinutesRemainingTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files: {0} ({1}).
        /// </summary>
        public static string ModFileTreeViewModel_StatusBar_Files__0__1 {
            get {
                return ResourceManager.GetString("ModFileTreeViewModel_StatusBar_Files__0__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Games.
        /// </summary>
        public static string MyGames {
            get {
                return ResourceManager.GetString("MyGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported Games.
        /// </summary>
        public static string MyGamesView__Detected_games {
            get {
                return ResourceManager.GetString("MyGamesView__Detected_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supported games have been added. No new games detected..
        /// </summary>
        public static string MyGamesView__NoGamesDetectedText {
            get {
                return ResourceManager.GetString("MyGamesView__NoGamesDetectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add games to start modding.
        /// </summary>
        public static string MyGamesView__NoGamesManagedText {
            get {
                return ResourceManager.GetString("MyGamesView__NoGamesManagedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add games to get started.
        /// </summary>
        public static string MyGamesView__Page_Description {
            get {
                return ResourceManager.GetString("MyGamesView__Page_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Added.
        /// </summary>
        public static string MyGamesView__Ready_to_mod {
            get {
                return ResourceManager.GetString("MyGamesView__Ready_to_mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add a game before using Loadouts.
        /// </summary>
        public static string MyLoadoutsEmptyState_Header {
            get {
                return ResourceManager.GetString("MyLoadoutsEmptyState_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loadouts enable you to switch between various play styles by customising each with different mods and configurations..
        /// </summary>
        public static string MyLoadoutsEmptyState_Subtitle {
            get {
                return ResourceManager.GetString("MyLoadoutsEmptyState_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Loadouts.
        /// </summary>
        public static string MyLoadoutsGameSectionHeading {
            get {
                return ResourceManager.GetString("MyLoadoutsGameSectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game Loadouts which contain their own individual mod preferences and settings. Switch between Loadouts and apply the one you want to play..
        /// </summary>
        public static string MyLoadoutsPageDescriptionText {
            get {
                return ResourceManager.GetString("MyLoadoutsPageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Loadouts.
        /// </summary>
        public static string MyLoadoutsPageTitle {
            get {
                return ResourceManager.GetString("MyLoadoutsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new panel.
        /// </summary>
        public static string NavigationControl_NavigationControl_Open_in_new_panel {
            get {
                return ResourceManager.GetString("NavigationControl_NavigationControl_Open_in_new_panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new tab.
        /// </summary>
        public static string NavigationControl_NavigationControl_Open_in_new_tab {
            get {
                return ResourceManager.GetString("NavigationControl_NavigationControl_Open_in_new_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsfeed.
        /// </summary>
        public static string Newsfeed {
            get {
                return ResourceManager.GetString("Newsfeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add panels for split screen viewing by selecting the.
        /// </summary>
        public static string NewTabPageInfoBannerText1 {
            get {
                return ResourceManager.GetString("NewTabPageInfoBannerText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button in the toolbar.
        /// </summary>
        public static string NewTabPageInfoBannerText2 {
            get {
                return ResourceManager.GetString("NewTabPageInfoBannerText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE.
        /// </summary>
        public static string Nexus_Premium_Status__Free {
            get {
                return ResourceManager.GetString("Nexus_Premium_Status__Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREMIUM.
        /// </summary>
        public static string Nexus_Premium_Status__Premium {
            get {
                return ResourceManager.GetString("Nexus_Premium_Status__Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPORTER.
        /// </summary>
        public static string Nexus_Premium_Status__Supporter {
            get {
                return ResourceManager.GetString("Nexus_Premium_Status__Supporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser didn&apos;t open automatically?.
        /// </summary>
        public static string NexusLoginOverlayView__BROWSER_DIDNT_OPEN {
            get {
                return ResourceManager.GetString("NexusLoginOverlayView__BROWSER_DIDNT_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &quot;Authorize&quot; on the website.
        /// </summary>
        public static string NexusLoginOverlayView__Please_Click_Authorize {
            get {
                return ResourceManager.GetString("NexusLoginOverlayView__Please_Click_Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please copy the following URL into your browser window. We support Chrome, Safari, Firefox and Edge..
        /// </summary>
        public static string NexusLoginOverlayView_Please_copy_url {
            get {
                return ResourceManager.GetString("NexusLoginOverlayView_Please_copy_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        public static string OpenDiscordMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenDiscordMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus Mods forums.
        /// </summary>
        public static string OpenForumsMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenForumsMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string OpenGitHubMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenGitHubMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status page.
        /// </summary>
        public static string OpenStatusPageMenuItem_Header {
            get {
                return ResourceManager.GetString("OpenStatusPageMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tab.
        /// </summary>
        public static string Panel_Add_tab_ToolTip {
            get {
                return ResourceManager.GetString("Panel_Add_tab_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tab.
        /// </summary>
        public static string PanelTabHeaderViewModel_Title_New_Tab {
            get {
                return ResourceManager.GetString("PanelTabHeaderViewModel_Title_New_Tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {1:0}%.
        /// </summary>
        public static string ProgressBar_ProgressTextFormat__Total_1_0 {
            get {
                return ResourceManager.GetString("ProgressBar_ProgressTextFormat__Total_1_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchBox__Search {
            get {
                return ResourceManager.GetString("SearchBox__Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will need to restart to apply this setting.
        /// </summary>
        public static string SettingEntryView_NeedRestartMessage {
            get {
                return ResourceManager.GetString("SettingEntryView_NeedRestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your preferences..
        /// </summary>
        public static string SettingsView_Description {
            get {
                return ResourceManager.GetString("SettingsView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Title {
            get {
                return ResourceManager.GetString("SettingsView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ShowWelcomeMessageMenuItem_Header {
            get {
                return ResourceManager.GetString("ShowWelcomeMessageMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string SpineDownloadButton_ToolTip {
            get {
                return ResourceManager.GetString("SpineDownloadButton_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string SpineHomeButton_ToolTip_Home {
            get {
                return ResourceManager.GetString("SpineHomeButton_ToolTip_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string StringFormatters__HoursRemaining__hours {
            get {
                return ResourceManager.GetString("StringFormatters__HoursRemaining__hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        public static string StringFormatters__In_progress__numDownloads {
            get {
                return ResourceManager.GetString("StringFormatters__In_progress__numDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins.
        /// </summary>
        public static string StringFormatters__MinutesRemaining_mins {
            get {
                return ResourceManager.GetString("StringFormatters__MinutesRemaining_mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} secs.
        /// </summary>
        public static string StringFormatters__SecondsRemaining_secs {
            get {
                return ResourceManager.GetString("StringFormatters__SecondsRemaining_secs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account settings.
        /// </summary>
        public static string TopBar_AccountSettings {
            get {
                return ResourceManager.GetString("TopBar_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TopBar_Back_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_Back_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string TopBar_Forward_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_Forward_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Premium.
        /// </summary>
        public static string TopBar_GetPremiumMenuItem {
            get {
                return ResourceManager.GetString("TopBar_GetPremiumMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to give feedback and help us improve..
        /// </summary>
        public static string TopBar_GiveFeedback_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_GiveFeedback_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help and feedback.
        /// </summary>
        public static string TopBar_Help_ToolTip {
            get {
                return ResourceManager.GetString("TopBar_Help_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string TopBar_MyProfile {
            get {
                return ResourceManager.GetString("TopBar_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string TopBar_SignOut {
            get {
                return ResourceManager.GetString("TopBar_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string TopBarActions__LOG_IN {
            get {
                return ResourceManager.GetString("TopBarActions__LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your Nexus Mods account.
        /// </summary>
        public static string TopBarActions__LOG_IN_ToolTip {
            get {
                return ResourceManager.GetString("TopBarActions__LOG_IN_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to uninstall the Nexus Mods app.
        /// </summary>
        public static string Updated_ViewUninstallDocs {
            get {
                return ResourceManager.GetString("Updated_ViewUninstallDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Updater_LATER {
            get {
                return ResourceManager.GetString("Updater_LATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important: In order to install this version you will need to uninstall first. This will delete all your mods..
        /// </summary>
        public static string Updater_MainMessage {
            get {
                return ResourceManager.GetString("Updater_MainMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View update.
        /// </summary>
        public static string Updater_UPDATE {
            get {
                return ResourceManager.GetString("Updater_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        public static string Updater_UpdateAvailable {
            get {
                return ResourceManager.GetString("Updater_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that your copy of the app was installed via a system managed package manager, please update via your operating system&apos;s update application..
        /// </summary>
        public static string Updater_UseSystemUpdater {
            get {
                return ResourceManager.GetString("Updater_UseSystemUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View changelog on GitHub.
        /// </summary>
        public static string Updater_ViewChangelog {
            get {
                return ResourceManager.GetString("Updater_ViewChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View app logs.
        /// </summary>
        public static string ViewAppLogsMenuItem_Header {
            get {
                return ResourceManager.GetString("ViewAppLogsMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View changelog.
        /// </summary>
        public static string ViewChangelogMenuItem_Header {
            get {
                return ResourceManager.GetString("ViewChangelogMenuItem.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string ViewModFilesView_Location {
            get {
                return ResourceManager.GetString("ViewModFilesView_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string ViewModFilesView_Locations {
            get {
                return ResourceManager.GetString("ViewModFilesView_Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Not Found.
        /// </summary>
        public static string ViewModInfoPage_NotFound_Title {
            get {
                return ResourceManager.GetString("ViewModInfoPage_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Info.
        /// </summary>
        public static string ViewModInfoPage_Title {
            get {
                return ResourceManager.GetString("ViewModInfoPage_Title", resourceCulture);
            }
        }
    }
}
