using System.Diagnostics;
using static NexusMods.Abstractions.Loadouts.Synchronizers.Rules.Actions;
using static NexusMods.Abstractions.Loadouts.Synchronizers.Rules.SignatureShorthand;

namespace NexusMods.Abstractions.Loadouts.Synchronizers.Rules;

public class ActionMapping
{

    /// <summary>
    /// Maps a signature to the corresponding actions
    /// </summary>
    public static Actions MapActions(Signature signature)
    {
        return MapActions((SignatureShorthand)signature);
    }

    /// <summary>
    /// Maps a shorthand signature to the corresponding actions
    /// </summary>
    public static Actions MapActions(SignatureShorthand shorthand)
    {
        Debug.Assert(Enum.IsDefined(shorthand), $"Unknown value: {shorthand} ({(int)shorthand})");
        
        // Format of the shorthand:
        // xxx_yyy_z -> xxx: Loadout, yyy: Archive, z: Ignore path
        // xxx: a tuple of `(Disk, Previous, Loadout)` states.
        // A `x` means no state because that source has no value for the path.
        // A `A`, `B`, `C` are placeholders for the hash of the file, so `AAA` means all three sources have the same hash, while `BAA` means the hash is different on disk
        // from either the previous state or the loadout.
        // yyy: a tuple of `(Disk, Previous, Loadout)` archive states. `XXX` means all three sources are archived (regardless of their hash) and `Xxx` means the disk is archived but the previous and loadout states are not.
        // `z`: either `i` or `I`, where `i` means the path is not ignored and `I` means the path is ignored.
        // The easiest way to think of this is that a capital letter means the existence of data, while a lowercase letter means the absence of data or a false value.
        return shorthand switch
        {
            xxA_xxx_iL => WarnOfUnableToExtract,
            xxx_xxx_iI => WriteIntrinsic,
            xxA_xxx_iI => WriteIntrinsic,
            xxA_xxx_iG => WarnOfUnableToExtract,
            xxA_xxX_iL => ExtractToDisk,
            xxA_xxX_iI => WriteIntrinsic,
            xxA_xxX_iG => ExtractToDisk,
            xxA_xxx_IL => WarnOfUnableToExtract,
            xxA_xxx_II => WriteIntrinsic,
            xxA_xxx_IG => WarnOfUnableToExtract,
            xxA_xxX_IL => ExtractToDisk,
            xxA_xxX_II => WriteIntrinsic,
            xxA_xxX_IG => ExtractToDisk,
            xAx_xxx_iL => DoNothing,
            xAx_xxx_iI => DoNothing,
            xAx_xxx_iG => DoNothing,
            xAx_xXx_iL => DoNothing,
            xAx_xXx_iI => DoNothing,
            xAx_xXx_iG => DoNothing,
            xAx_xxx_IL => DoNothing,
            xAx_xxx_II => DoNothing,
            xAx_xxx_IG => DoNothing,
            xAx_xXx_IL => DoNothing,
            xAx_xXx_II => DoNothing,
            xAx_xXx_IG => DoNothing,
            xAA_xxx_iL => WarnOfUnableToExtract,
            xAA_xxx_iI => WriteIntrinsic,
            xAA_xxx_iG => WarnOfUnableToExtract,
            xAA_xXX_iL => AddReifiedDelete,
            xAA_xXX_iI => WriteIntrinsic,
            xAA_xXX_iG => AddReifiedDelete,
            xAA_xxx_IL => AddReifiedDelete,
            xAA_xxx_II => WriteIntrinsic,
            xAA_xxx_IG => AddReifiedDelete,
            xAA_xXX_IL => AddReifiedDelete,
            xAA_xXX_II => WriteIntrinsic,
            xAA_xXX_IG => AddReifiedDelete,
            xAB_xxx_iL => WarnOfUnableToExtract,
            xAB_xxx_iI => WriteIntrinsic,
            xAB_xxx_iG => WarnOfUnableToExtract,
            xAB_xXx_iL => WarnOfUnableToExtract,
            xAB_xXx_iI => WriteIntrinsic,
            xAB_xXx_iG => WarnOfUnableToExtract,
            xAB_xxX_iL => ExtractToDisk,
            xAB_xxX_iI => WriteIntrinsic,
            xAB_xxX_iG => ExtractToDisk,
            xAB_xXX_iL => ExtractToDisk,
            xAB_xXX_iI => WriteIntrinsic,
            xAB_xXX_iG => ExtractToDisk,
            xAB_xxx_IL => WarnOfUnableToExtract,
            xAB_xxx_II => WriteIntrinsic,
            xAB_xxx_IG => WarnOfUnableToExtract,
            xAB_xXx_IL => WarnOfUnableToExtract,
            xAB_xXx_II => WriteIntrinsic,
            xAB_xXx_IG => WarnOfUnableToExtract,
            xAB_xxX_IL => ExtractToDisk,
            xAB_xxX_II => WriteIntrinsic,
            xAB_xxX_IG => ExtractToDisk,
            xAB_xXX_IL => ExtractToDisk,
            xAB_xXX_II => WriteIntrinsic,
            xAB_xXX_IG => ExtractToDisk,
            Axx_xxx_iL => BackupFile | IngestFromDisk,
            Axx_xxx_iI => AdaptLoadout,
            Axx_xxx_iG => BackupFile | IngestFromDisk,
            Axx_Xxx_iL => IngestFromDisk,
            Axx_Xxx_iI => AdaptLoadout,
            Axx_Xxx_iG => IngestFromDisk,
            Axx_xxx_IL => IngestFromDisk,
            Axx_xxx_II => AdaptLoadout,
            Axx_xxx_IG => IngestFromDisk,
            Axx_Xxx_IL => IngestFromDisk,
            Axx_Xxx_II => AdaptLoadout,
            Axx_Xxx_IG => IngestFromDisk,
            AxA_xxx_iL => BackupFile,
            AxA_xxx_iI => DoNothing,
            AxA_xxx_iG => DoNothing,
            AxA_XxX_iL => DoNothing,
            AxA_XxX_iI => DoNothing,
            AxA_XxX_iG => DoNothing,
            AxA_xxx_IL => DoNothing,
            AxA_xxx_II => DoNothing,
            AxA_xxx_IG => DoNothing,
            AxA_XxX_IL => DoNothing,
            AxA_XxX_II => DoNothing,
            AxA_XxX_IG => DoNothing,
            AxB_xxx_iL => BackupFile | IngestFromDisk,
            AxB_xxx_iI => AdaptLoadout,
            AxB_xxx_iG => BackupFile | IngestFromDisk,
            AxB_Xxx_iL => IngestFromDisk,
            AxB_Xxx_iI => AdaptLoadout,
            AxB_Xxx_iG => IngestFromDisk,
            AxB_xxX_iL => BackupFile | IngestFromDisk,
            AxB_xxX_iI => AdaptLoadout,
            AxB_xxX_iG => BackupFile | IngestFromDisk,
            AxB_XxX_iL => IngestFromDisk,
            AxB_XxX_iI => AdaptLoadout,
            AxB_XxX_iG => IngestFromDisk,
            AxB_xxx_IL => BackupFile | IngestFromDisk,
            AxB_xxx_II => AdaptLoadout,
            AxB_xxx_IG => BackupFile | IngestFromDisk,
            AxB_Xxx_IL => BackupFile | IngestFromDisk,
            AxB_Xxx_II => AdaptLoadout,
            AxB_Xxx_IG => BackupFile | IngestFromDisk,
            AxB_xxX_IL => BackupFile | DeleteFromDisk | ExtractToDisk,
            AxB_xxX_II => WriteIntrinsic,
            AxB_xxX_IG => BackupFile | DeleteFromDisk | ExtractToDisk,
            AxB_XxX_IL => BackupFile | DeleteFromDisk | ExtractToDisk,
            AxB_XxX_II => WriteIntrinsic,
            AxB_XxX_IG => BackupFile | DeleteFromDisk | ExtractToDisk,
            AAx_xxx_iL => BackupFile | DeleteFromDisk,
            AAx_xxx_iI => DoNothing,
            AAx_xxx_iG => BackupFile | DeleteFromDisk,
            AAx_XXx_iL => DeleteFromDisk,
            AAx_XXx_iI => DoNothing,
            AAx_XXx_iG => DeleteFromDisk,
            AAx_xxx_IL => BackupFile | DeleteFromDisk,
            AAx_xxx_II => DoNothing,
            AAx_xxx_IG => BackupFile | DeleteFromDisk,
            AAx_XXx_IL => DeleteFromDisk,
            AAx_XXx_II => DoNothing,
            AAx_XXx_IG => DeleteFromDisk,
            AAA_xxx_iL => DoNothing,
            AAA_xxx_iI => DoNothing,
            AAA_xxx_iG => DoNothing,
            AAA_XXX_iL => DoNothing,
            AAA_XXX_iI => DoNothing,
            AAA_XXX_iG => DoNothing,
            AAA_xxx_IL => DoNothing,
            AAA_xxx_II => DoNothing,
            AAA_xxx_IG => DoNothing,
            AAA_XXX_IL => DoNothing,
            AAA_XXX_II => DoNothing,
            AAA_XXX_IG => DoNothing,
            AAB_xxx_iL => WarnOfUnableToExtract,
            AAB_xxx_iI => WriteIntrinsic,
            AAB_xxx_iG => WarnOfUnableToExtract,
            AAB_XXx_iL => WarnOfUnableToExtract,
            AAB_XXx_iI => WriteIntrinsic,
            AAB_XXx_iG => WarnOfUnableToExtract,
            AAB_xxX_iL => BackupFile | DeleteFromDisk | ExtractToDisk,
            AAB_xxX_iI => WriteIntrinsic,
            AAB_xxX_iG => BackupFile | DeleteFromDisk | ExtractToDisk,
            AAB_XXX_iL => DeleteFromDisk | ExtractToDisk,
            AAB_XXX_iI => WriteIntrinsic,
            AAB_XXX_iG => DeleteFromDisk | ExtractToDisk,
            AAB_xxx_IL => WarnOfUnableToExtract,
            AAB_xxx_II => WriteIntrinsic,
            AAB_xxx_IG => WarnOfUnableToExtract,
            AAB_XXx_IL => WarnOfUnableToExtract,
            AAB_XXx_II => WriteIntrinsic,
            AAB_XXx_IG => WarnOfUnableToExtract,
            AAB_xxX_IL => BackupFile | DeleteFromDisk | ExtractToDisk,
            AAB_xxX_II => WriteIntrinsic,
            AAB_xxX_IG => BackupFile | DeleteFromDisk | ExtractToDisk,
            AAB_XXX_IL => DeleteFromDisk | ExtractToDisk,
            AAB_XXX_II => WriteIntrinsic,
            AAB_XXX_IG => DeleteFromDisk | ExtractToDisk,
            ABx_xxx_iL => BackupFile | DeleteFromDisk,
            ABx_xxx_iI => DoNothing,
            ABx_xxx_iG => BackupFile | DeleteFromDisk,
            ABx_Xxx_iL => DeleteFromDisk,
            ABx_Xxx_iI => DoNothing,
            ABx_Xxx_iG => DeleteFromDisk,
            ABx_xXx_iL => BackupFile | DeleteFromDisk,
            ABx_xXx_iI => DoNothing,
            ABx_xXx_iG => BackupFile | DeleteFromDisk,
            ABx_XXx_iL => DeleteFromDisk,
            ABx_XXx_iI => DoNothing,
            ABx_XXx_iG => DeleteFromDisk,
            ABx_xxx_IL => BackupFile | DeleteFromDisk,
            ABx_xxx_II => DoNothing,
            ABx_xxx_IG => BackupFile | DeleteFromDisk,
            ABx_Xxx_IL => DeleteFromDisk,
            ABx_Xxx_II => DoNothing,
            ABx_Xxx_IG => DeleteFromDisk,
            ABx_xXx_IL => BackupFile | DeleteFromDisk,
            ABx_xXx_II => DoNothing,
            ABx_xXx_IG => BackupFile | DeleteFromDisk,
            ABx_XXx_IL => DeleteFromDisk,
            ABx_XXx_II => DoNothing,
            ABx_XXx_IG => DeleteFromDisk,
            ABA_xxx_iL => BackupFile,
            ABA_xxx_iI => DoNothing,
            ABA_xxx_iG => DoNothing,
            ABA_XxX_iL => DoNothing,
            ABA_XxX_iI => DoNothing,
            ABA_XxX_iG => DoNothing,
            ABA_xXx_iL => BackupFile,
            ABA_xXx_iI => DoNothing,
            ABA_xXx_iG => DoNothing,
            ABA_XXX_iL => DoNothing,
            ABA_XXX_iI => DoNothing,
            ABA_XXX_iG => DoNothing,
            ABA_xxx_IL => DoNothing,
            ABA_xxx_II => DoNothing,
            ABA_xxx_IG => DoNothing,
            ABA_XxX_IL => DoNothing,
            ABA_XxX_II => DoNothing,
            ABA_XxX_IG => DoNothing,
            ABA_xXx_IL => DoNothing,
            ABA_xXx_II => DoNothing,
            ABA_xXx_IG => DoNothing,
            ABA_XXX_IL => DoNothing,
            ABA_XXX_II => DoNothing,
            ABA_XXX_IG => DoNothing,
            ABB_xxx_iL => BackupFile | IngestFromDisk,
            ABB_xxx_iI => AdaptLoadout,
            ABB_xxx_iG => BackupFile | IngestFromDisk,
            ABB_Xxx_iL => IngestFromDisk,
            ABB_Xxx_iI => AdaptLoadout,
            ABB_Xxx_iG => IngestFromDisk,
            ABB_xXX_iL => BackupFile | IngestFromDisk,
            ABB_xXX_iI => AdaptLoadout,
            ABB_xXX_iG => BackupFile | IngestFromDisk,
            ABB_XXX_iL => IngestFromDisk,
            ABB_XXX_iI => AdaptLoadout,
            ABB_XXX_iG => IngestFromDisk,
            ABB_xxx_IL => BackupFile | IngestFromDisk,
            ABB_xxx_II => AdaptLoadout,
            ABB_xxx_IG => BackupFile | IngestFromDisk,
            ABB_Xxx_IL => IngestFromDisk,
            ABB_Xxx_II => AdaptLoadout,
            ABB_Xxx_IG => IngestFromDisk,
            ABB_xXX_IL => BackupFile | IngestFromDisk,
            ABB_xXX_II => AdaptLoadout,
            ABB_xXX_IG => BackupFile | IngestFromDisk,
            ABB_XXX_IL => IngestFromDisk,
            ABB_XXX_II => AdaptLoadout,
            ABB_XXX_IG => IngestFromDisk,
            ABC_xxx_iL => WarnOfConflict,
            ABC_xxx_iI => WriteIntrinsic,
            ABC_xxx_iG => WarnOfConflict,
            ABC_Xxx_iL => WarnOfUnableToExtract,
            ABC_Xxx_iI => WriteIntrinsic,
            ABC_Xxx_iG => WarnOfUnableToExtract,
            ABC_xXx_iL => WarnOfConflict,
            ABC_xXx_iI => WarnOfConflict,
            ABC_xXx_iG => WarnOfConflict,
            ABC_xxX_iL => BackupFile | IngestFromDisk,
            ABC_xxX_iI => AdaptLoadout,
            ABC_xxX_iG => BackupFile | IngestFromDisk,
            ABC_XXx_iL => BackupFile | IngestFromDisk,
            ABC_XXx_iI => AdaptLoadout,
            ABC_XXx_iG => BackupFile | IngestFromDisk,
            ABC_XxX_iL => WarnOfConflict,
            ABC_XxX_iI => WarnOfConflict,
            ABC_XxX_iG => WarnOfConflict,
            ABC_xXX_iL => BackupFile | IngestFromDisk,
            ABC_xXX_iI => AdaptLoadout,
            ABC_xXX_iG => BackupFile | IngestFromDisk,
            ABC_XXX_iL => IngestFromDisk,
            ABC_XXX_iI => AdaptLoadout,
            ABC_XXX_iG => IngestFromDisk,
            ABC_xxx_IL => BackupFile | IngestFromDisk,
            ABC_xxx_II => AdaptLoadout,
            ABC_xxx_IG => BackupFile | IngestFromDisk,
            ABC_Xxx_IL => WarnOfUnableToExtract,
            ABC_Xxx_II => WriteIntrinsic,
            ABC_Xxx_IG => WarnOfUnableToExtract,
            ABC_xXx_IL => WarnOfUnableToExtract,
            ABC_xXx_II => WriteIntrinsic,
            ABC_xXx_IG => WarnOfUnableToExtract,
            ABC_xxX_IL => BackupFile | DeleteFromDisk | ExtractToDisk,
            ABC_xxX_II => WriteIntrinsic,
            ABC_xxX_IG => BackupFile | DeleteFromDisk | ExtractToDisk,
            ABC_XXx_IL => WarnOfUnableToExtract,
            ABC_XXx_II => WriteIntrinsic,
            ABC_XXx_IG => WarnOfUnableToExtract,
            ABC_XxX_IL => DeleteFromDisk | ExtractToDisk,
            ABC_XxX_II => WriteIntrinsic,
            ABC_XxX_IG => DeleteFromDisk | ExtractToDisk,
            ABC_xXX_IL => BackupFile | DeleteFromDisk | ExtractToDisk,
            ABC_xXX_II => WriteIntrinsic,
            ABC_xXX_IG => BackupFile | DeleteFromDisk | ExtractToDisk,
            ABC_XXX_IL => DeleteFromDisk | ExtractToDisk,
            ABC_XXX_II => WriteIntrinsic,
            ABC_XXX_IG => DeleteFromDisk | ExtractToDisk,
        };
    }
}
