using NexusMods.Hashing.xxHash64;
using NexusMods.Paths;

namespace NexusMods.DataModel.Games;

/// <summary>
/// A game file that has been hashed, used to recognize files that are unmodified from the base
/// game. Generated by GenerateGameFileHashes verb.
/// </summary>
/// <param name="Path"></param>
/// <param name="Hash"></param>
/// <param name="Size"></param>
public record HashedGameFile()
{
    /// <summary>
    /// The path of the file
    /// </summary>
    public required GamePath Path { get; init; }

    /// <summary>
    /// The hash of the file.
    /// </summary>
    public required Hash Hash { get; init; }

    /// <summary>
    /// The size of the file.
    /// </summary>
    public required Size Size { get; init; }
}
