//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusMods.Games.FOMOD.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NexusMods.Games.FOMOD.UI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GuidedInstallerStepView_GuidedInstallerStepView_Installation_complete {
            get {
                return ResourceManager.GetString("GuidedInstallerStepView_GuidedInstallerStepView_Installation_complete", resourceCulture);
            }
        }
        
        public static string FooterStepperView_FooterStepperView_Finish {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_Finish", resourceCulture);
            }
        }
        
        public static string FooterStepperView_FooterStepperView_Next {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_Next", resourceCulture);
            }
        }
        
        public static string FooterStepperView_FooterStepperView_Previous {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_Previous", resourceCulture);
            }
        }
        
        public static string GuidedInstallerGroupView_SelectAtLeastOne {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupView_SelectAtLeastOne", resourceCulture);
            }
        }
        
        public static string GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_None {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_None", resourceCulture);
            }
        }
        
        public static string GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Select_nothing {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Select_nothing", resourceCulture);
            }
        }
        
        public static string GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Use_this_option_to_select_nothing {
            get {
                return ResourceManager.GetString("GuidedInstallerGroupViewModel_GuidedInstallerGroupViewModel_Use_this_option_to_se" +
                        "lect_nothing", resourceCulture);
            }
        }
        
        public static string GuidedInstallerStepView_GuidedInstallerStepView_No_additional_details_available {
            get {
                return ResourceManager.GetString("GuidedInstallerStepView_GuidedInstallerStepView_No_additional_details_available", resourceCulture);
            }
        }
        
        public static string FooterStepperView_FooterStepperView_One_or_more_groups_failed_validation_ {
            get {
                return ResourceManager.GetString("FooterStepperView_FooterStepperView_One_or_more_groups_failed_validation_", resourceCulture);
            }
        }
    }
}
