//HintName: DiagnosticTemplateAttribute.g.cs
// <auto-generated/>

namespace NexusMods.Generators.Diagnostics
{
    /// <summary>
    /// Indicates that field is a diagnostic template.
    /// </summary>
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage(Justification = "Auto-generated")]
    [global::System.AttributeUsage(global::System.AttributeTargets.Field)]
    internal class DiagnosticTemplateAttribute : global::System.Attribute { }
}
