name: Build Linux (PupNet)

on:
  workflow_call:
    inputs:
      AppVersion:
        type: string
        required: false
        description: "The version of the application to build"
        default: "1.0.0"
      Target:
        description: "The git ref to base the release on (eg: '1957a8e7', default: current head of the branch the workflow is run on)"
        required: false
        type: string
      PupNetRepo:
        type: string
        required: false
        description: "The URL of the PupNet repository"
        default: "https://github.com/kuiperzone/PupNet-Deploy.git"
      PupNetBranch:
        type: string
        required: false
        description: "The branch or commit of PupNet to use"
        default: "dabed0cc2063c5a2d2c4f780bb6718f4b90cfd16"
      ProjectFile:
        type: string
        required: true
        description: "The relative path to the project to build"
      RetentionDays:
        type: number
        required: false
        default: 1
        description: "The amount of days for the artifact to persist"
      BuildAppImage:
        type: boolean
        description: "Build an AppImage?"
        required: false
        default: true
      BuildArchive:
        type: boolean
        description: "Build an Archive?"
        required: false
        default: true
    outputs:
      ArtifactNameLinuxArchive:
        description: "Name of the Artifact that contains the Linux Archive"
        value: ${{ jobs.build-archive.outputs.artifactName }}
      ArtifactUrlLinuxArchive:
        description: "URL to download the Linux Archive artifact"
        value: ${{ jobs.build-archive.outputs.artifactUrl }}
      ArtifactNameLinuxAppImage:
        description: "Name of the Artifact that contains the Linux AppImage"
        value: ${{ jobs.build-appimage.outputs.artifactName }}
      ArtifactUrlLinuxAppImage:
        description: "URL to download the Linux AppImage artifact"
        value: ${{ jobs.build-appimage.outputs.artifactUrl }}

jobs:
  build-archive:
    if: inputs.BuildArchive
    runs-on: ubuntu-latest
    outputs:
      artifactName: ${{ steps.setOutputs.outputs.artifactName }}
      artifactUrl: ${{ steps.upload.outputs.artifact-url }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.Target || github.sha }}
          submodules: "recursive"
          
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        id: stepid
        with:
          dotnet-version: '9.x'
          
      - name: Print debug info
        run: dotnet --info          

      - name: Transform inputs
        id: transformInputs
        shell: pwsh
        env:
          ProjectFile: ${{ inputs.ProjectFile }}
        run: |
          $projectDir = [System.IO.Path]::GetDirectoryName("$env:ProjectFile")
          $projectName = [System.IO.Path]::GetFileNameWithoutExtension("$env:ProjectFile")
          echo "projectDir=$projectDir" >> $env:GITHUB_OUTPUT
          echo "projectName=$projectName" >> $env:GITHUB_OUTPUT

      - name: Build & Install PupNet
        run: |
          # Our use of central package management may cause PupNet to fail build
          # so we lift it out to a separate directory and build it there
          mkdir ../PupNet
          cd ../PupNet
          git clone ${{ inputs.PupNetRepo }} .
          git checkout ${{ inputs.PupNetBranch }}
          dotnet pack -c Release -o . -p:Version=0.0.0-nma
          dotnet tool install --global --add-source . KuiperZone.PupNet --version 0.0.0-nma

      - name: Create Archive
        working-directory: ${{ steps.transformInputs.outputs.projectDir }}
        run: pupnet -y -v ${{ inputs.AppVersion }} -k zip -p DefineConstants=INSTALLATION_METHOD_ARCHIVE

      - name: Set outputs
        id: setOutputs
        shell: pwsh
        run: |
          echo "artifactName=${{ steps.transformInputs.outputs.projectName }}-${{ inputs.Target || github.sha }}-Linux-Archive" >> $env:GITHUB_OUTPUT

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setOutputs.outputs.artifactName }}
          path: ${{ steps.transformInputs.outputs.projectDir }}/Deploy/OUT/*.zip
          if-no-files-found: error
          retention-days: ${{ inputs.RetentionDays }}

  build-appimage:
    if: inputs.BuildAppImage
    runs-on: ubuntu-latest
    outputs:
      artifactName: ${{ steps.setOutputs.outputs.artifactName }}
      artifactUrl: ${{ steps.upload.outputs.artifact-url }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.Target || github.sha }}
          submodules: "recursive"
          
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        id: stepid
        with:
          dotnet-version: '9.x'

      - name: Print debug info
        run: dotnet --info          

      - name: Transform inputs
        id: transformInputs
        shell: pwsh
        env:
          ProjectFile: ${{ inputs.ProjectFile }}
        run: |
          $projectDir = [System.IO.Path]::GetDirectoryName("$env:ProjectFile")
          $projectName = [System.IO.Path]::GetFileNameWithoutExtension("$env:ProjectFile")
          echo "projectDir=$projectDir" >> $env:GITHUB_OUTPUT
          echo "projectName=$projectName" >> $env:GITHUB_OUTPUT

      # https://github.com/AppImage/AppImageKit/wiki/FUSE#install-fuse
      - name: Install FUSE
        run: sudo add-apt-repository universe && sudo apt install libfuse2

      - name: Build & Install PupNet
        run: |
          # Our use of central package management may cause PupNet to fail build
          # so we lift it out to a separate directory and build it there
          mkdir ../PupNet
          cd ../PupNet
          git clone ${{ inputs.PupNetRepo }} .
          git checkout ${{ inputs.PupNetBranch }}
          dotnet pack -c Release -o . -p:Version=0.0.0-nma
          dotnet tool install --global --add-source . KuiperZone.PupNet --version 0.0.0-nma

      - name: Create AppImage
        working-directory: ${{ steps.transformInputs.outputs.projectDir }}
        run: pupnet -y -v ${{ inputs.AppVersion }} -k AppImage -p DefineConstants=INSTALLATION_METHOD_APPIMAGE

      - name: Set outputs
        id: setOutputs
        shell: pwsh
        run: |
          echo "artifactName=${{ steps.transformInputs.outputs.projectName }}-${{ inputs.Target || github.sha }}-Linux-AppImage" >> $env:GITHUB_OUTPUT

      - name: Upload
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setOutputs.outputs.artifactName }}
          path: ${{ steps.transformInputs.outputs.projectDir }}/Deploy/OUT/*.AppImage
          if-no-files-found: error
          retention-days: ${{ inputs.RetentionDays }}
