name: Build Linux (PupNet)

on:
  workflow_call:
    inputs:
      AppVersion:
        type: string
        required: false
        description: "The version of the application to build"
        default: "1.0.0"
      PupNetRepo:
        type: string
        required: false
        description: "The URL of the PupNet repository"
        default: "https://github.com/kuiperzone/PupNet-Deploy.git"
      PupNetBranch:
        type: string
        required: false
        description: "The branch or commit of PupNet to use"
        default: "dabed0cc2063c5a2d2c4f780bb6718f4b90cfd16"
      ProjectFile:
        type: string
        required: true
        description: "The relative path to the project to build"
      RetentionDays:
        type: number
        required: false
        default: 1
        description: "The amount of days for the artifact to persist"
      BuildAppImage:
        type: boolean
        description: "Build an AppImage?"
        required: false
        default: true
      BuildArchive:
        type: boolean
        description: "Build an Archive?"
        required: false
        default: true
    outputs:
      ArtifactNameLinuxArchive:
        description: "Name of the Artifact that contains the Linux Archive"
        value: ${{ jobs.build.outputs.artifactNameLinuxArchive }}
      ArtifactNameLinuxAppImage:
        description: "Name of the Artifact that contains the Linux AppImage"
        value: ${{ jobs.build.outputs.artifactNameLinuxAppImage }}
      ArtifactUrlLinuxArchive:
        description: "URL to download the Linux Archive artifact"
        value: ${{ jobs.build.outputs.artifactUrlLinuxArchive }}
      ArtifactUrlLinuxAppImage:
        description: "URL to download the Linux AppImage artifact"
        value: ${{ jobs.build.outputs.artifactUrlLinuxAppImage }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifactNameLinuxArchive: ${{ steps.setOutputs.outputs.artifactNameLinuxArchive }}
      artifactNameLinuxAppImage: ${{ steps.setOutputs.outputs.artifactNameLinuxAppImage }}
      artifactUrlLinuxArchive: ${{ steps.uploadArchive.outputs.artifact-url }}
      artifactUrlLinuxAppImage: ${{ steps.uploadAppImage.outputs.artifact-url }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Transform inputs
        id: transformInputs
        shell: pwsh
        env:
          ProjectFile: ${{ inputs.ProjectFile }}
        run: |
          $projectDir = [System.IO.Path]::GetDirectoryName("$env:ProjectFile")
          $projectName = [System.IO.Path]::GetFileNameWithoutExtension("$env:ProjectFile")
          echo "projectDir=$projectDir" >> $env:GITHUB_OUTPUT
          echo "projectName=$projectName" >> $env:GITHUB_OUTPUT

      - name: Print debug info
        run: dotnet --info

      # https://github.com/AppImage/AppImageKit/wiki/FUSE#install-fuse
      - name: Install FUSE
        run: sudo add-apt-repository universe && sudo apt install libfuse2

      - name: Build & Install PupNet
        run: |
          # Our use of central package management may cause PupNet to fail build
          # so we lift it out to a separate directory and build it there
          mkdir ../PupNet
          cd ../PupNet
          git clone ${{ inputs.PupNetRepo }} .
          git checkout ${{ inputs.PupNetBranch }}
          dotnet pack -c Release -o . -p:Version=0.0.0-nma
          dotnet tool install --global --add-source . KuiperZone.PupNet --version 0.0.0-nma

      - name: Create Archive
        if: ${{ inputs.BuildArchive }}
        working-directory: ${{ steps.transformInputs.outputs.projectDir }}
        run: pupnet -y -v ${{ inputs.AppVersion }} -k zip -p DefineConstants=INSTALLATION_METHOD_ARCHIVE

      - name: Create AppImage
        if: ${{ inputs.BuildAppImage }}
        working-directory: ${{ steps.transformInputs.outputs.projectDir }}
        run: pupnet -y -v ${{ inputs.AppVersion }} -k AppImage -p DefineConstants=INSTALLATION_METHOD_APPIMAGE

      - name: Set outputs
        id: setOutputs
        shell: pwsh
        run: |
          echo "artifactNameLinuxArchive=${{ steps.transformInputs.outputs.projectName }}-${{ github.sha }}-Linux-Archive" >> $env:GITHUB_OUTPUT
          echo "artifactNameLinuxAppImage=${{ steps.transformInputs.outputs.projectName }}-${{ github.sha }}-Linux-AppImage" >> $env:GITHUB_OUTPUT

      - name: Upload Archive
        id: uploadArchive
        if: ${{ inputs.BuildArchive }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setOutputs.outputs.artifactNameLinuxArchive }}
          path: ${{ steps.transformInputs.outputs.projectDir }}/Deploy/OUT/*.zip
          if-no-files-found: error
          retention-days: ${{ inputs.RetentionDays }}

      - name: Upload AppImage
        id: uploadAppImage
        if: ${{ inputs.BuildAppImage }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setOutputs.outputs.artifactNameLinuxAppImage }}
          path: ${{ steps.transformInputs.outputs.projectDir }}/Deploy/OUT/*.AppImage
          if-no-files-found: error
          retention-days: ${{ inputs.RetentionDays }}
