name: Game Environment Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VERSION: 3.0.1.8

jobs:
  build:
    
    name: Test ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-game-env]

    steps:
      - uses: actions/checkout@v3

      - name: Set Permissions
        if: runner.os != 'Windows'
        run: chmod -R +x src/ArchiveManagement/NexusMods.FileExtractor/Extractors

      - name: Tests
        run: dotnet test --filter RequiresGameInstalls=True