name: Validate codecov.yaml

on:
  push:
    paths:
      - "codecov.yaml"
      - ".github/workflows/validate-codecov.yaml"
    branches: [ main ]
  pull_request:
    paths:
      - "codecov.yaml"
      - ".github/workflows/validate-codecov.yaml"
    branches: [ main ]

jobs:
  validate:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/validate-codecov.yaml@f4285cadcc379247b7c2ba6a35e5b34639fa5481
