name: Validate Changelog Assets

on:
  push:
    branches: [ main ]
    paths:
      - "docs/changelog-assets/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"

    steps:
      - name: Validate
        shell: bash
        run: ./scripts/changelog-prepare-assets.sh verify
