name: Validate Changelog Assets

on:
  push:
    branches: [ main ]
    paths:
      - "docs/changelog-assets/**"
      - ".github/workflows/validate-changelog-assets.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - "docs/changelog-assets/**"
      - ".github/workflows/validate-changelog-assets.yaml"
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - name: Validate
        shell: bash
        run: ./scripts/changelog-prepare-assets.sh verify
